// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/cloud_account.proto
// generatedFile: aviatrix/config/v1alpha/cloud_account_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/cloud_account_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudAccountService_CreateCloudAccount_FullMethodName = "/aviatrix.config.v1alpha.CloudAccountService/CreateCloudAccount"
	CloudAccountService_UpdateCloudAccount_FullMethodName = "/aviatrix.config.v1alpha.CloudAccountService/UpdateCloudAccount"
	CloudAccountService_ListCloudAccounts_FullMethodName  = "/aviatrix.config.v1alpha.CloudAccountService/ListCloudAccounts"
	CloudAccountService_CountCloudAccounts_FullMethodName = "/aviatrix.config.v1alpha.CloudAccountService/CountCloudAccounts"
	CloudAccountService_GetCloudAccount_FullMethodName    = "/aviatrix.config.v1alpha.CloudAccountService/GetCloudAccount"
	CloudAccountService_DeleteCloudAccount_FullMethodName = "/aviatrix.config.v1alpha.CloudAccountService/DeleteCloudAccount"
)

// CloudAccountServiceClient is the client API for CloudAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type CloudAccountServiceClient interface {
	CreateCloudAccount(ctx context.Context, in *CreateCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error)
	UpdateCloudAccount(ctx context.Context, in *UpdateCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error)
	ListCloudAccounts(ctx context.Context, in *ListCloudAccountsRequest, opts ...grpc.CallOption) (*ListCloudAccountsResponse, error)
	CountCloudAccounts(ctx context.Context, in *CountCloudAccountsRequest, opts ...grpc.CallOption) (*CountCloudAccountsResponse, error)
	GetCloudAccount(ctx context.Context, in *GetCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error)
	DeleteCloudAccount(ctx context.Context, in *DeleteCloudAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cloudAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudAccountServiceClient(cc grpc.ClientConnInterface) CloudAccountServiceClient {
	return &cloudAccountServiceClient{cc}
}

func (c *cloudAccountServiceClient) CreateCloudAccount(ctx context.Context, in *CreateCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudAccount)
	err := c.cc.Invoke(ctx, CloudAccountService_CreateCloudAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAccountServiceClient) UpdateCloudAccount(ctx context.Context, in *UpdateCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudAccount)
	err := c.cc.Invoke(ctx, CloudAccountService_UpdateCloudAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAccountServiceClient) ListCloudAccounts(ctx context.Context, in *ListCloudAccountsRequest, opts ...grpc.CallOption) (*ListCloudAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCloudAccountsResponse)
	err := c.cc.Invoke(ctx, CloudAccountService_ListCloudAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAccountServiceClient) CountCloudAccounts(ctx context.Context, in *CountCloudAccountsRequest, opts ...grpc.CallOption) (*CountCloudAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountCloudAccountsResponse)
	err := c.cc.Invoke(ctx, CloudAccountService_CountCloudAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAccountServiceClient) GetCloudAccount(ctx context.Context, in *GetCloudAccountRequest, opts ...grpc.CallOption) (*CloudAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudAccount)
	err := c.cc.Invoke(ctx, CloudAccountService_GetCloudAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAccountServiceClient) DeleteCloudAccount(ctx context.Context, in *DeleteCloudAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CloudAccountService_DeleteCloudAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudAccountServiceServer is the server API for CloudAccountService service.
// All implementations must embed UnimplementedCloudAccountServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type CloudAccountServiceServer interface {
	CreateCloudAccount(context.Context, *CreateCloudAccountRequest) (*CloudAccount, error)
	UpdateCloudAccount(context.Context, *UpdateCloudAccountRequest) (*CloudAccount, error)
	ListCloudAccounts(context.Context, *ListCloudAccountsRequest) (*ListCloudAccountsResponse, error)
	CountCloudAccounts(context.Context, *CountCloudAccountsRequest) (*CountCloudAccountsResponse, error)
	GetCloudAccount(context.Context, *GetCloudAccountRequest) (*CloudAccount, error)
	DeleteCloudAccount(context.Context, *DeleteCloudAccountRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCloudAccountServiceServer()
}

// UnimplementedCloudAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudAccountServiceServer struct{}

func (UnimplementedCloudAccountServiceServer) CreateCloudAccount(context.Context, *CreateCloudAccountRequest) (*CloudAccount, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCloudAccount not implemented")
}
func (UnimplementedCloudAccountServiceServer) UpdateCloudAccount(context.Context, *UpdateCloudAccountRequest) (*CloudAccount, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCloudAccount not implemented")
}
func (UnimplementedCloudAccountServiceServer) ListCloudAccounts(context.Context, *ListCloudAccountsRequest) (*ListCloudAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCloudAccounts not implemented")
}
func (UnimplementedCloudAccountServiceServer) CountCloudAccounts(context.Context, *CountCloudAccountsRequest) (*CountCloudAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountCloudAccounts not implemented")
}
func (UnimplementedCloudAccountServiceServer) GetCloudAccount(context.Context, *GetCloudAccountRequest) (*CloudAccount, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloudAccount not implemented")
}
func (UnimplementedCloudAccountServiceServer) DeleteCloudAccount(context.Context, *DeleteCloudAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCloudAccount not implemented")
}
func (UnimplementedCloudAccountServiceServer) mustEmbedUnimplementedCloudAccountServiceServer() {}
func (UnimplementedCloudAccountServiceServer) testEmbeddedByValue()                             {}

// UnsafeCloudAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudAccountServiceServer will
// result in compilation errors.
type UnsafeCloudAccountServiceServer interface {
	mustEmbedUnimplementedCloudAccountServiceServer()
}

func RegisterCloudAccountServiceServer(s grpc.ServiceRegistrar, srv CloudAccountServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudAccountService_ServiceDesc, srv)
}

func _CloudAccountService_CreateCloudAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCloudAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).CreateCloudAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_CreateCloudAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).CreateCloudAccount(ctx, req.(*CreateCloudAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAccountService_UpdateCloudAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCloudAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).UpdateCloudAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_UpdateCloudAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).UpdateCloudAccount(ctx, req.(*UpdateCloudAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAccountService_ListCloudAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCloudAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).ListCloudAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_ListCloudAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).ListCloudAccounts(ctx, req.(*ListCloudAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAccountService_CountCloudAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountCloudAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).CountCloudAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_CountCloudAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).CountCloudAccounts(ctx, req.(*CountCloudAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAccountService_GetCloudAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).GetCloudAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_GetCloudAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).GetCloudAccount(ctx, req.(*GetCloudAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAccountService_DeleteCloudAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCloudAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAccountServiceServer).DeleteCloudAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAccountService_DeleteCloudAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAccountServiceServer).DeleteCloudAccount(ctx, req.(*DeleteCloudAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudAccountService_ServiceDesc is the grpc.ServiceDesc for CloudAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.CloudAccountService",
	HandlerType: (*CloudAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCloudAccount",
			Handler:    _CloudAccountService_CreateCloudAccount_Handler,
		},
		{
			MethodName: "UpdateCloudAccount",
			Handler:    _CloudAccountService_UpdateCloudAccount_Handler,
		},
		{
			MethodName: "ListCloudAccounts",
			Handler:    _CloudAccountService_ListCloudAccounts_Handler,
		},
		{
			MethodName: "CountCloudAccounts",
			Handler:    _CloudAccountService_CountCloudAccounts_Handler,
		},
		{
			MethodName: "GetCloudAccount",
			Handler:    _CloudAccountService_GetCloudAccount_Handler,
		},
		{
			MethodName: "DeleteCloudAccount",
			Handler:    _CloudAccountService_DeleteCloudAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/cloud_account_service_gen.proto",
}
