// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_list.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_list_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/dcf_policy_list_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DcfPolicyListService_CreateDcfPolicyList_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyListService/CreateDcfPolicyList"
	DcfPolicyListService_UpdateDcfPolicyList_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyListService/UpdateDcfPolicyList"
	DcfPolicyListService_ListDcfPolicyLists_FullMethodName  = "/aviatrix.config.v1alpha.DcfPolicyListService/ListDcfPolicyLists"
	DcfPolicyListService_CountDcfPolicyLists_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyListService/CountDcfPolicyLists"
	DcfPolicyListService_GetDcfPolicyList_FullMethodName    = "/aviatrix.config.v1alpha.DcfPolicyListService/GetDcfPolicyList"
	DcfPolicyListService_DeleteDcfPolicyList_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyListService/DeleteDcfPolicyList"
)

// DcfPolicyListServiceClient is the client API for DcfPolicyListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type DcfPolicyListServiceClient interface {
	CreateDcfPolicyList(ctx context.Context, in *CreateDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error)
	UpdateDcfPolicyList(ctx context.Context, in *UpdateDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error)
	ListDcfPolicyLists(ctx context.Context, in *ListDcfPolicyListsRequest, opts ...grpc.CallOption) (*ListDcfPolicyListsResponse, error)
	CountDcfPolicyLists(ctx context.Context, in *CountDcfPolicyListsRequest, opts ...grpc.CallOption) (*CountDcfPolicyListsResponse, error)
	GetDcfPolicyList(ctx context.Context, in *GetDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error)
	DeleteDcfPolicyList(ctx context.Context, in *DeleteDcfPolicyListRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dcfPolicyListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDcfPolicyListServiceClient(cc grpc.ClientConnInterface) DcfPolicyListServiceClient {
	return &dcfPolicyListServiceClient{cc}
}

func (c *dcfPolicyListServiceClient) CreateDcfPolicyList(ctx context.Context, in *CreateDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyList)
	err := c.cc.Invoke(ctx, DcfPolicyListService_CreateDcfPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyListServiceClient) UpdateDcfPolicyList(ctx context.Context, in *UpdateDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyList)
	err := c.cc.Invoke(ctx, DcfPolicyListService_UpdateDcfPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyListServiceClient) ListDcfPolicyLists(ctx context.Context, in *ListDcfPolicyListsRequest, opts ...grpc.CallOption) (*ListDcfPolicyListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDcfPolicyListsResponse)
	err := c.cc.Invoke(ctx, DcfPolicyListService_ListDcfPolicyLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyListServiceClient) CountDcfPolicyLists(ctx context.Context, in *CountDcfPolicyListsRequest, opts ...grpc.CallOption) (*CountDcfPolicyListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountDcfPolicyListsResponse)
	err := c.cc.Invoke(ctx, DcfPolicyListService_CountDcfPolicyLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyListServiceClient) GetDcfPolicyList(ctx context.Context, in *GetDcfPolicyListRequest, opts ...grpc.CallOption) (*DcfPolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyList)
	err := c.cc.Invoke(ctx, DcfPolicyListService_GetDcfPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyListServiceClient) DeleteDcfPolicyList(ctx context.Context, in *DeleteDcfPolicyListRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DcfPolicyListService_DeleteDcfPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DcfPolicyListServiceServer is the server API for DcfPolicyListService service.
// All implementations must embed UnimplementedDcfPolicyListServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type DcfPolicyListServiceServer interface {
	CreateDcfPolicyList(context.Context, *CreateDcfPolicyListRequest) (*DcfPolicyList, error)
	UpdateDcfPolicyList(context.Context, *UpdateDcfPolicyListRequest) (*DcfPolicyList, error)
	ListDcfPolicyLists(context.Context, *ListDcfPolicyListsRequest) (*ListDcfPolicyListsResponse, error)
	CountDcfPolicyLists(context.Context, *CountDcfPolicyListsRequest) (*CountDcfPolicyListsResponse, error)
	GetDcfPolicyList(context.Context, *GetDcfPolicyListRequest) (*DcfPolicyList, error)
	DeleteDcfPolicyList(context.Context, *DeleteDcfPolicyListRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDcfPolicyListServiceServer()
}

// UnimplementedDcfPolicyListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDcfPolicyListServiceServer struct{}

func (UnimplementedDcfPolicyListServiceServer) CreateDcfPolicyList(context.Context, *CreateDcfPolicyListRequest) (*DcfPolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDcfPolicyList not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) UpdateDcfPolicyList(context.Context, *UpdateDcfPolicyListRequest) (*DcfPolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDcfPolicyList not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) ListDcfPolicyLists(context.Context, *ListDcfPolicyListsRequest) (*ListDcfPolicyListsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDcfPolicyLists not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) CountDcfPolicyLists(context.Context, *CountDcfPolicyListsRequest) (*CountDcfPolicyListsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountDcfPolicyLists not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) GetDcfPolicyList(context.Context, *GetDcfPolicyListRequest) (*DcfPolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDcfPolicyList not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) DeleteDcfPolicyList(context.Context, *DeleteDcfPolicyListRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDcfPolicyList not implemented")
}
func (UnimplementedDcfPolicyListServiceServer) mustEmbedUnimplementedDcfPolicyListServiceServer() {}
func (UnimplementedDcfPolicyListServiceServer) testEmbeddedByValue()                              {}

// UnsafeDcfPolicyListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DcfPolicyListServiceServer will
// result in compilation errors.
type UnsafeDcfPolicyListServiceServer interface {
	mustEmbedUnimplementedDcfPolicyListServiceServer()
}

func RegisterDcfPolicyListServiceServer(s grpc.ServiceRegistrar, srv DcfPolicyListServiceServer) {
	// If the following call panics, it indicates UnimplementedDcfPolicyListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DcfPolicyListService_ServiceDesc, srv)
}

func _DcfPolicyListService_CreateDcfPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDcfPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).CreateDcfPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_CreateDcfPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).CreateDcfPolicyList(ctx, req.(*CreateDcfPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyListService_UpdateDcfPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDcfPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).UpdateDcfPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_UpdateDcfPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).UpdateDcfPolicyList(ctx, req.(*UpdateDcfPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyListService_ListDcfPolicyLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDcfPolicyListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).ListDcfPolicyLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_ListDcfPolicyLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).ListDcfPolicyLists(ctx, req.(*ListDcfPolicyListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyListService_CountDcfPolicyLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountDcfPolicyListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).CountDcfPolicyLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_CountDcfPolicyLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).CountDcfPolicyLists(ctx, req.(*CountDcfPolicyListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyListService_GetDcfPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDcfPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).GetDcfPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_GetDcfPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).GetDcfPolicyList(ctx, req.(*GetDcfPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyListService_DeleteDcfPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDcfPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyListServiceServer).DeleteDcfPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyListService_DeleteDcfPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyListServiceServer).DeleteDcfPolicyList(ctx, req.(*DeleteDcfPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DcfPolicyListService_ServiceDesc is the grpc.ServiceDesc for DcfPolicyListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DcfPolicyListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.DcfPolicyListService",
	HandlerType: (*DcfPolicyListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDcfPolicyList",
			Handler:    _DcfPolicyListService_CreateDcfPolicyList_Handler,
		},
		{
			MethodName: "UpdateDcfPolicyList",
			Handler:    _DcfPolicyListService_UpdateDcfPolicyList_Handler,
		},
		{
			MethodName: "ListDcfPolicyLists",
			Handler:    _DcfPolicyListService_ListDcfPolicyLists_Handler,
		},
		{
			MethodName: "CountDcfPolicyLists",
			Handler:    _DcfPolicyListService_CountDcfPolicyLists_Handler,
		},
		{
			MethodName: "GetDcfPolicyList",
			Handler:    _DcfPolicyListService_GetDcfPolicyList_Handler,
		},
		{
			MethodName: "DeleteDcfPolicyList",
			Handler:    _DcfPolicyListService_DeleteDcfPolicyList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/dcf_policy_list_service_gen.proto",
}
