// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_block.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_block_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/dcf_policy_block_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DcfPolicyBlockService_CreateDcfPolicyBlock_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyBlockService/CreateDcfPolicyBlock"
	DcfPolicyBlockService_UpdateDcfPolicyBlock_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyBlockService/UpdateDcfPolicyBlock"
	DcfPolicyBlockService_ListDcfPolicyBlocks_FullMethodName  = "/aviatrix.config.v1alpha.DcfPolicyBlockService/ListDcfPolicyBlocks"
	DcfPolicyBlockService_CountDcfPolicyBlocks_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyBlockService/CountDcfPolicyBlocks"
	DcfPolicyBlockService_GetDcfPolicyBlock_FullMethodName    = "/aviatrix.config.v1alpha.DcfPolicyBlockService/GetDcfPolicyBlock"
	DcfPolicyBlockService_DeleteDcfPolicyBlock_FullMethodName = "/aviatrix.config.v1alpha.DcfPolicyBlockService/DeleteDcfPolicyBlock"
)

// DcfPolicyBlockServiceClient is the client API for DcfPolicyBlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type DcfPolicyBlockServiceClient interface {
	CreateDcfPolicyBlock(ctx context.Context, in *CreateDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error)
	UpdateDcfPolicyBlock(ctx context.Context, in *UpdateDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error)
	ListDcfPolicyBlocks(ctx context.Context, in *ListDcfPolicyBlocksRequest, opts ...grpc.CallOption) (*ListDcfPolicyBlocksResponse, error)
	CountDcfPolicyBlocks(ctx context.Context, in *CountDcfPolicyBlocksRequest, opts ...grpc.CallOption) (*CountDcfPolicyBlocksResponse, error)
	GetDcfPolicyBlock(ctx context.Context, in *GetDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error)
	DeleteDcfPolicyBlock(ctx context.Context, in *DeleteDcfPolicyBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dcfPolicyBlockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDcfPolicyBlockServiceClient(cc grpc.ClientConnInterface) DcfPolicyBlockServiceClient {
	return &dcfPolicyBlockServiceClient{cc}
}

func (c *dcfPolicyBlockServiceClient) CreateDcfPolicyBlock(ctx context.Context, in *CreateDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyBlock)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_CreateDcfPolicyBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyBlockServiceClient) UpdateDcfPolicyBlock(ctx context.Context, in *UpdateDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyBlock)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_UpdateDcfPolicyBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyBlockServiceClient) ListDcfPolicyBlocks(ctx context.Context, in *ListDcfPolicyBlocksRequest, opts ...grpc.CallOption) (*ListDcfPolicyBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDcfPolicyBlocksResponse)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_ListDcfPolicyBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyBlockServiceClient) CountDcfPolicyBlocks(ctx context.Context, in *CountDcfPolicyBlocksRequest, opts ...grpc.CallOption) (*CountDcfPolicyBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountDcfPolicyBlocksResponse)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_CountDcfPolicyBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyBlockServiceClient) GetDcfPolicyBlock(ctx context.Context, in *GetDcfPolicyBlockRequest, opts ...grpc.CallOption) (*DcfPolicyBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DcfPolicyBlock)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_GetDcfPolicyBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcfPolicyBlockServiceClient) DeleteDcfPolicyBlock(ctx context.Context, in *DeleteDcfPolicyBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DcfPolicyBlockService_DeleteDcfPolicyBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DcfPolicyBlockServiceServer is the server API for DcfPolicyBlockService service.
// All implementations must embed UnimplementedDcfPolicyBlockServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type DcfPolicyBlockServiceServer interface {
	CreateDcfPolicyBlock(context.Context, *CreateDcfPolicyBlockRequest) (*DcfPolicyBlock, error)
	UpdateDcfPolicyBlock(context.Context, *UpdateDcfPolicyBlockRequest) (*DcfPolicyBlock, error)
	ListDcfPolicyBlocks(context.Context, *ListDcfPolicyBlocksRequest) (*ListDcfPolicyBlocksResponse, error)
	CountDcfPolicyBlocks(context.Context, *CountDcfPolicyBlocksRequest) (*CountDcfPolicyBlocksResponse, error)
	GetDcfPolicyBlock(context.Context, *GetDcfPolicyBlockRequest) (*DcfPolicyBlock, error)
	DeleteDcfPolicyBlock(context.Context, *DeleteDcfPolicyBlockRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDcfPolicyBlockServiceServer()
}

// UnimplementedDcfPolicyBlockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDcfPolicyBlockServiceServer struct{}

func (UnimplementedDcfPolicyBlockServiceServer) CreateDcfPolicyBlock(context.Context, *CreateDcfPolicyBlockRequest) (*DcfPolicyBlock, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDcfPolicyBlock not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) UpdateDcfPolicyBlock(context.Context, *UpdateDcfPolicyBlockRequest) (*DcfPolicyBlock, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDcfPolicyBlock not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) ListDcfPolicyBlocks(context.Context, *ListDcfPolicyBlocksRequest) (*ListDcfPolicyBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDcfPolicyBlocks not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) CountDcfPolicyBlocks(context.Context, *CountDcfPolicyBlocksRequest) (*CountDcfPolicyBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountDcfPolicyBlocks not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) GetDcfPolicyBlock(context.Context, *GetDcfPolicyBlockRequest) (*DcfPolicyBlock, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDcfPolicyBlock not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) DeleteDcfPolicyBlock(context.Context, *DeleteDcfPolicyBlockRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDcfPolicyBlock not implemented")
}
func (UnimplementedDcfPolicyBlockServiceServer) mustEmbedUnimplementedDcfPolicyBlockServiceServer() {}
func (UnimplementedDcfPolicyBlockServiceServer) testEmbeddedByValue()                               {}

// UnsafeDcfPolicyBlockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DcfPolicyBlockServiceServer will
// result in compilation errors.
type UnsafeDcfPolicyBlockServiceServer interface {
	mustEmbedUnimplementedDcfPolicyBlockServiceServer()
}

func RegisterDcfPolicyBlockServiceServer(s grpc.ServiceRegistrar, srv DcfPolicyBlockServiceServer) {
	// If the following call panics, it indicates UnimplementedDcfPolicyBlockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DcfPolicyBlockService_ServiceDesc, srv)
}

func _DcfPolicyBlockService_CreateDcfPolicyBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDcfPolicyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).CreateDcfPolicyBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_CreateDcfPolicyBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).CreateDcfPolicyBlock(ctx, req.(*CreateDcfPolicyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyBlockService_UpdateDcfPolicyBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDcfPolicyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).UpdateDcfPolicyBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_UpdateDcfPolicyBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).UpdateDcfPolicyBlock(ctx, req.(*UpdateDcfPolicyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyBlockService_ListDcfPolicyBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDcfPolicyBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).ListDcfPolicyBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_ListDcfPolicyBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).ListDcfPolicyBlocks(ctx, req.(*ListDcfPolicyBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyBlockService_CountDcfPolicyBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountDcfPolicyBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).CountDcfPolicyBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_CountDcfPolicyBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).CountDcfPolicyBlocks(ctx, req.(*CountDcfPolicyBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyBlockService_GetDcfPolicyBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDcfPolicyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).GetDcfPolicyBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_GetDcfPolicyBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).GetDcfPolicyBlock(ctx, req.(*GetDcfPolicyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcfPolicyBlockService_DeleteDcfPolicyBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDcfPolicyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcfPolicyBlockServiceServer).DeleteDcfPolicyBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcfPolicyBlockService_DeleteDcfPolicyBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcfPolicyBlockServiceServer).DeleteDcfPolicyBlock(ctx, req.(*DeleteDcfPolicyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DcfPolicyBlockService_ServiceDesc is the grpc.ServiceDesc for DcfPolicyBlockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DcfPolicyBlockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.DcfPolicyBlockService",
	HandlerType: (*DcfPolicyBlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDcfPolicyBlock",
			Handler:    _DcfPolicyBlockService_CreateDcfPolicyBlock_Handler,
		},
		{
			MethodName: "UpdateDcfPolicyBlock",
			Handler:    _DcfPolicyBlockService_UpdateDcfPolicyBlock_Handler,
		},
		{
			MethodName: "ListDcfPolicyBlocks",
			Handler:    _DcfPolicyBlockService_ListDcfPolicyBlocks_Handler,
		},
		{
			MethodName: "CountDcfPolicyBlocks",
			Handler:    _DcfPolicyBlockService_CountDcfPolicyBlocks_Handler,
		},
		{
			MethodName: "GetDcfPolicyBlock",
			Handler:    _DcfPolicyBlockService_GetDcfPolicyBlock_Handler,
		},
		{
			MethodName: "DeleteDcfPolicyBlock",
			Handler:    _DcfPolicyBlockService_DeleteDcfPolicyBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/dcf_policy_block_service_gen.proto",
}
