// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/network_inspection.proto
// generatedFile: aviatrix/config/v1alpha/network_inspection_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/network_inspection_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkInspectionService_CreateNetworkInspection_FullMethodName = "/aviatrix.config.v1alpha.NetworkInspectionService/CreateNetworkInspection"
	NetworkInspectionService_UpdateNetworkInspection_FullMethodName = "/aviatrix.config.v1alpha.NetworkInspectionService/UpdateNetworkInspection"
	NetworkInspectionService_ListNetworkInspections_FullMethodName  = "/aviatrix.config.v1alpha.NetworkInspectionService/ListNetworkInspections"
	NetworkInspectionService_CountNetworkInspections_FullMethodName = "/aviatrix.config.v1alpha.NetworkInspectionService/CountNetworkInspections"
	NetworkInspectionService_GetNetworkInspection_FullMethodName    = "/aviatrix.config.v1alpha.NetworkInspectionService/GetNetworkInspection"
	NetworkInspectionService_DeleteNetworkInspection_FullMethodName = "/aviatrix.config.v1alpha.NetworkInspectionService/DeleteNetworkInspection"
)

// NetworkInspectionServiceClient is the client API for NetworkInspectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type NetworkInspectionServiceClient interface {
	CreateNetworkInspection(ctx context.Context, in *CreateNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error)
	UpdateNetworkInspection(ctx context.Context, in *UpdateNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error)
	ListNetworkInspections(ctx context.Context, in *ListNetworkInspectionsRequest, opts ...grpc.CallOption) (*ListNetworkInspectionsResponse, error)
	CountNetworkInspections(ctx context.Context, in *CountNetworkInspectionsRequest, opts ...grpc.CallOption) (*CountNetworkInspectionsResponse, error)
	GetNetworkInspection(ctx context.Context, in *GetNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error)
	DeleteNetworkInspection(ctx context.Context, in *DeleteNetworkInspectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkInspectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkInspectionServiceClient(cc grpc.ClientConnInterface) NetworkInspectionServiceClient {
	return &networkInspectionServiceClient{cc}
}

func (c *networkInspectionServiceClient) CreateNetworkInspection(ctx context.Context, in *CreateNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInspection)
	err := c.cc.Invoke(ctx, NetworkInspectionService_CreateNetworkInspection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInspectionServiceClient) UpdateNetworkInspection(ctx context.Context, in *UpdateNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInspection)
	err := c.cc.Invoke(ctx, NetworkInspectionService_UpdateNetworkInspection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInspectionServiceClient) ListNetworkInspections(ctx context.Context, in *ListNetworkInspectionsRequest, opts ...grpc.CallOption) (*ListNetworkInspectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkInspectionsResponse)
	err := c.cc.Invoke(ctx, NetworkInspectionService_ListNetworkInspections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInspectionServiceClient) CountNetworkInspections(ctx context.Context, in *CountNetworkInspectionsRequest, opts ...grpc.CallOption) (*CountNetworkInspectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountNetworkInspectionsResponse)
	err := c.cc.Invoke(ctx, NetworkInspectionService_CountNetworkInspections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInspectionServiceClient) GetNetworkInspection(ctx context.Context, in *GetNetworkInspectionRequest, opts ...grpc.CallOption) (*NetworkInspection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInspection)
	err := c.cc.Invoke(ctx, NetworkInspectionService_GetNetworkInspection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkInspectionServiceClient) DeleteNetworkInspection(ctx context.Context, in *DeleteNetworkInspectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetworkInspectionService_DeleteNetworkInspection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkInspectionServiceServer is the server API for NetworkInspectionService service.
// All implementations must embed UnimplementedNetworkInspectionServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type NetworkInspectionServiceServer interface {
	CreateNetworkInspection(context.Context, *CreateNetworkInspectionRequest) (*NetworkInspection, error)
	UpdateNetworkInspection(context.Context, *UpdateNetworkInspectionRequest) (*NetworkInspection, error)
	ListNetworkInspections(context.Context, *ListNetworkInspectionsRequest) (*ListNetworkInspectionsResponse, error)
	CountNetworkInspections(context.Context, *CountNetworkInspectionsRequest) (*CountNetworkInspectionsResponse, error)
	GetNetworkInspection(context.Context, *GetNetworkInspectionRequest) (*NetworkInspection, error)
	DeleteNetworkInspection(context.Context, *DeleteNetworkInspectionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNetworkInspectionServiceServer()
}

// UnimplementedNetworkInspectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkInspectionServiceServer struct{}

func (UnimplementedNetworkInspectionServiceServer) CreateNetworkInspection(context.Context, *CreateNetworkInspectionRequest) (*NetworkInspection, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetworkInspection not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) UpdateNetworkInspection(context.Context, *UpdateNetworkInspectionRequest) (*NetworkInspection, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNetworkInspection not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) ListNetworkInspections(context.Context, *ListNetworkInspectionsRequest) (*ListNetworkInspectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworkInspections not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) CountNetworkInspections(context.Context, *CountNetworkInspectionsRequest) (*CountNetworkInspectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountNetworkInspections not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) GetNetworkInspection(context.Context, *GetNetworkInspectionRequest) (*NetworkInspection, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkInspection not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) DeleteNetworkInspection(context.Context, *DeleteNetworkInspectionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetworkInspection not implemented")
}
func (UnimplementedNetworkInspectionServiceServer) mustEmbedUnimplementedNetworkInspectionServiceServer() {
}
func (UnimplementedNetworkInspectionServiceServer) testEmbeddedByValue() {}

// UnsafeNetworkInspectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkInspectionServiceServer will
// result in compilation errors.
type UnsafeNetworkInspectionServiceServer interface {
	mustEmbedUnimplementedNetworkInspectionServiceServer()
}

func RegisterNetworkInspectionServiceServer(s grpc.ServiceRegistrar, srv NetworkInspectionServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkInspectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkInspectionService_ServiceDesc, srv)
}

func _NetworkInspectionService_CreateNetworkInspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).CreateNetworkInspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_CreateNetworkInspection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).CreateNetworkInspection(ctx, req.(*CreateNetworkInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInspectionService_UpdateNetworkInspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNetworkInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).UpdateNetworkInspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_UpdateNetworkInspection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).UpdateNetworkInspection(ctx, req.(*UpdateNetworkInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInspectionService_ListNetworkInspections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkInspectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).ListNetworkInspections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_ListNetworkInspections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).ListNetworkInspections(ctx, req.(*ListNetworkInspectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInspectionService_CountNetworkInspections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountNetworkInspectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).CountNetworkInspections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_CountNetworkInspections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).CountNetworkInspections(ctx, req.(*CountNetworkInspectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInspectionService_GetNetworkInspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).GetNetworkInspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_GetNetworkInspection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).GetNetworkInspection(ctx, req.(*GetNetworkInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkInspectionService_DeleteNetworkInspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInspectionServiceServer).DeleteNetworkInspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkInspectionService_DeleteNetworkInspection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInspectionServiceServer).DeleteNetworkInspection(ctx, req.(*DeleteNetworkInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkInspectionService_ServiceDesc is the grpc.ServiceDesc for NetworkInspectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkInspectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.NetworkInspectionService",
	HandlerType: (*NetworkInspectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNetworkInspection",
			Handler:    _NetworkInspectionService_CreateNetworkInspection_Handler,
		},
		{
			MethodName: "UpdateNetworkInspection",
			Handler:    _NetworkInspectionService_UpdateNetworkInspection_Handler,
		},
		{
			MethodName: "ListNetworkInspections",
			Handler:    _NetworkInspectionService_ListNetworkInspections_Handler,
		},
		{
			MethodName: "CountNetworkInspections",
			Handler:    _NetworkInspectionService_CountNetworkInspections_Handler,
		},
		{
			MethodName: "GetNetworkInspection",
			Handler:    _NetworkInspectionService_GetNetworkInspection_Handler,
		},
		{
			MethodName: "DeleteNetworkInspection",
			Handler:    _NetworkInspectionService_DeleteNetworkInspection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/network_inspection_service_gen.proto",
}
