// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/smart_group.proto
// generatedFile: aviatrix/config/v1alpha/smart_group_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/smart_group_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartGroupService_CreateSmartGroup_FullMethodName = "/aviatrix.config.v1alpha.SmartGroupService/CreateSmartGroup"
	SmartGroupService_UpdateSmartGroup_FullMethodName = "/aviatrix.config.v1alpha.SmartGroupService/UpdateSmartGroup"
	SmartGroupService_ListSmartGroups_FullMethodName  = "/aviatrix.config.v1alpha.SmartGroupService/ListSmartGroups"
	SmartGroupService_CountSmartGroups_FullMethodName = "/aviatrix.config.v1alpha.SmartGroupService/CountSmartGroups"
	SmartGroupService_GetSmartGroup_FullMethodName    = "/aviatrix.config.v1alpha.SmartGroupService/GetSmartGroup"
	SmartGroupService_DeleteSmartGroup_FullMethodName = "/aviatrix.config.v1alpha.SmartGroupService/DeleteSmartGroup"
)

// SmartGroupServiceClient is the client API for SmartGroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type SmartGroupServiceClient interface {
	CreateSmartGroup(ctx context.Context, in *CreateSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error)
	UpdateSmartGroup(ctx context.Context, in *UpdateSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error)
	ListSmartGroups(ctx context.Context, in *ListSmartGroupsRequest, opts ...grpc.CallOption) (*ListSmartGroupsResponse, error)
	CountSmartGroups(ctx context.Context, in *CountSmartGroupsRequest, opts ...grpc.CallOption) (*CountSmartGroupsResponse, error)
	GetSmartGroup(ctx context.Context, in *GetSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error)
	DeleteSmartGroup(ctx context.Context, in *DeleteSmartGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type smartGroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartGroupServiceClient(cc grpc.ClientConnInterface) SmartGroupServiceClient {
	return &smartGroupServiceClient{cc}
}

func (c *smartGroupServiceClient) CreateSmartGroup(ctx context.Context, in *CreateSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmartGroup)
	err := c.cc.Invoke(ctx, SmartGroupService_CreateSmartGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartGroupServiceClient) UpdateSmartGroup(ctx context.Context, in *UpdateSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmartGroup)
	err := c.cc.Invoke(ctx, SmartGroupService_UpdateSmartGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartGroupServiceClient) ListSmartGroups(ctx context.Context, in *ListSmartGroupsRequest, opts ...grpc.CallOption) (*ListSmartGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSmartGroupsResponse)
	err := c.cc.Invoke(ctx, SmartGroupService_ListSmartGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartGroupServiceClient) CountSmartGroups(ctx context.Context, in *CountSmartGroupsRequest, opts ...grpc.CallOption) (*CountSmartGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountSmartGroupsResponse)
	err := c.cc.Invoke(ctx, SmartGroupService_CountSmartGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartGroupServiceClient) GetSmartGroup(ctx context.Context, in *GetSmartGroupRequest, opts ...grpc.CallOption) (*SmartGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmartGroup)
	err := c.cc.Invoke(ctx, SmartGroupService_GetSmartGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartGroupServiceClient) DeleteSmartGroup(ctx context.Context, in *DeleteSmartGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SmartGroupService_DeleteSmartGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartGroupServiceServer is the server API for SmartGroupService service.
// All implementations must embed UnimplementedSmartGroupServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type SmartGroupServiceServer interface {
	CreateSmartGroup(context.Context, *CreateSmartGroupRequest) (*SmartGroup, error)
	UpdateSmartGroup(context.Context, *UpdateSmartGroupRequest) (*SmartGroup, error)
	ListSmartGroups(context.Context, *ListSmartGroupsRequest) (*ListSmartGroupsResponse, error)
	CountSmartGroups(context.Context, *CountSmartGroupsRequest) (*CountSmartGroupsResponse, error)
	GetSmartGroup(context.Context, *GetSmartGroupRequest) (*SmartGroup, error)
	DeleteSmartGroup(context.Context, *DeleteSmartGroupRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSmartGroupServiceServer()
}

// UnimplementedSmartGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartGroupServiceServer struct{}

func (UnimplementedSmartGroupServiceServer) CreateSmartGroup(context.Context, *CreateSmartGroupRequest) (*SmartGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSmartGroup not implemented")
}
func (UnimplementedSmartGroupServiceServer) UpdateSmartGroup(context.Context, *UpdateSmartGroupRequest) (*SmartGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSmartGroup not implemented")
}
func (UnimplementedSmartGroupServiceServer) ListSmartGroups(context.Context, *ListSmartGroupsRequest) (*ListSmartGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSmartGroups not implemented")
}
func (UnimplementedSmartGroupServiceServer) CountSmartGroups(context.Context, *CountSmartGroupsRequest) (*CountSmartGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountSmartGroups not implemented")
}
func (UnimplementedSmartGroupServiceServer) GetSmartGroup(context.Context, *GetSmartGroupRequest) (*SmartGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSmartGroup not implemented")
}
func (UnimplementedSmartGroupServiceServer) DeleteSmartGroup(context.Context, *DeleteSmartGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSmartGroup not implemented")
}
func (UnimplementedSmartGroupServiceServer) mustEmbedUnimplementedSmartGroupServiceServer() {}
func (UnimplementedSmartGroupServiceServer) testEmbeddedByValue()                           {}

// UnsafeSmartGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartGroupServiceServer will
// result in compilation errors.
type UnsafeSmartGroupServiceServer interface {
	mustEmbedUnimplementedSmartGroupServiceServer()
}

func RegisterSmartGroupServiceServer(s grpc.ServiceRegistrar, srv SmartGroupServiceServer) {
	// If the following call panics, it indicates UnimplementedSmartGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartGroupService_ServiceDesc, srv)
}

func _SmartGroupService_CreateSmartGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSmartGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).CreateSmartGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_CreateSmartGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).CreateSmartGroup(ctx, req.(*CreateSmartGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartGroupService_UpdateSmartGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSmartGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).UpdateSmartGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_UpdateSmartGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).UpdateSmartGroup(ctx, req.(*UpdateSmartGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartGroupService_ListSmartGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSmartGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).ListSmartGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_ListSmartGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).ListSmartGroups(ctx, req.(*ListSmartGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartGroupService_CountSmartGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountSmartGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).CountSmartGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_CountSmartGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).CountSmartGroups(ctx, req.(*CountSmartGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartGroupService_GetSmartGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSmartGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).GetSmartGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_GetSmartGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).GetSmartGroup(ctx, req.(*GetSmartGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartGroupService_DeleteSmartGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSmartGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartGroupServiceServer).DeleteSmartGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartGroupService_DeleteSmartGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartGroupServiceServer).DeleteSmartGroup(ctx, req.(*DeleteSmartGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartGroupService_ServiceDesc is the grpc.ServiceDesc for SmartGroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartGroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.SmartGroupService",
	HandlerType: (*SmartGroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSmartGroup",
			Handler:    _SmartGroupService_CreateSmartGroup_Handler,
		},
		{
			MethodName: "UpdateSmartGroup",
			Handler:    _SmartGroupService_UpdateSmartGroup_Handler,
		},
		{
			MethodName: "ListSmartGroups",
			Handler:    _SmartGroupService_ListSmartGroups_Handler,
		},
		{
			MethodName: "CountSmartGroups",
			Handler:    _SmartGroupService_CountSmartGroups_Handler,
		},
		{
			MethodName: "GetSmartGroup",
			Handler:    _SmartGroupService_GetSmartGroup_Handler,
		},
		{
			MethodName: "DeleteSmartGroup",
			Handler:    _SmartGroupService_DeleteSmartGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/smart_group_service_gen.proto",
}
