// Code generated by protoc-gen-proto-service. DO NOT EDIT.
// source: aviatrix/config/v1alpha/web_group.proto
// generatedFile: aviatrix/config/v1alpha/web_group_service_gen.proto

// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aviatrix/config/v1alpha/web_group_service_gen.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebGroupService_CreateWebGroup_FullMethodName = "/aviatrix.config.v1alpha.WebGroupService/CreateWebGroup"
	WebGroupService_UpdateWebGroup_FullMethodName = "/aviatrix.config.v1alpha.WebGroupService/UpdateWebGroup"
	WebGroupService_ListWebGroups_FullMethodName  = "/aviatrix.config.v1alpha.WebGroupService/ListWebGroups"
	WebGroupService_CountWebGroups_FullMethodName = "/aviatrix.config.v1alpha.WebGroupService/CountWebGroups"
	WebGroupService_GetWebGroup_FullMethodName    = "/aviatrix.config.v1alpha.WebGroupService/GetWebGroup"
	WebGroupService_DeleteWebGroup_FullMethodName = "/aviatrix.config.v1alpha.WebGroupService/DeleteWebGroup"
)

// WebGroupServiceClient is the client API for WebGroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Config service will host all Configuration object manipulation APIs.
type WebGroupServiceClient interface {
	CreateWebGroup(ctx context.Context, in *CreateWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error)
	UpdateWebGroup(ctx context.Context, in *UpdateWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error)
	ListWebGroups(ctx context.Context, in *ListWebGroupsRequest, opts ...grpc.CallOption) (*ListWebGroupsResponse, error)
	CountWebGroups(ctx context.Context, in *CountWebGroupsRequest, opts ...grpc.CallOption) (*CountWebGroupsResponse, error)
	GetWebGroup(ctx context.Context, in *GetWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error)
	DeleteWebGroup(ctx context.Context, in *DeleteWebGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type webGroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebGroupServiceClient(cc grpc.ClientConnInterface) WebGroupServiceClient {
	return &webGroupServiceClient{cc}
}

func (c *webGroupServiceClient) CreateWebGroup(ctx context.Context, in *CreateWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGroup)
	err := c.cc.Invoke(ctx, WebGroupService_CreateWebGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webGroupServiceClient) UpdateWebGroup(ctx context.Context, in *UpdateWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGroup)
	err := c.cc.Invoke(ctx, WebGroupService_UpdateWebGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webGroupServiceClient) ListWebGroups(ctx context.Context, in *ListWebGroupsRequest, opts ...grpc.CallOption) (*ListWebGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebGroupsResponse)
	err := c.cc.Invoke(ctx, WebGroupService_ListWebGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webGroupServiceClient) CountWebGroups(ctx context.Context, in *CountWebGroupsRequest, opts ...grpc.CallOption) (*CountWebGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountWebGroupsResponse)
	err := c.cc.Invoke(ctx, WebGroupService_CountWebGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webGroupServiceClient) GetWebGroup(ctx context.Context, in *GetWebGroupRequest, opts ...grpc.CallOption) (*WebGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebGroup)
	err := c.cc.Invoke(ctx, WebGroupService_GetWebGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webGroupServiceClient) DeleteWebGroup(ctx context.Context, in *DeleteWebGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WebGroupService_DeleteWebGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebGroupServiceServer is the server API for WebGroupService service.
// All implementations must embed UnimplementedWebGroupServiceServer
// for forward compatibility.
//
// Config service will host all Configuration object manipulation APIs.
type WebGroupServiceServer interface {
	CreateWebGroup(context.Context, *CreateWebGroupRequest) (*WebGroup, error)
	UpdateWebGroup(context.Context, *UpdateWebGroupRequest) (*WebGroup, error)
	ListWebGroups(context.Context, *ListWebGroupsRequest) (*ListWebGroupsResponse, error)
	CountWebGroups(context.Context, *CountWebGroupsRequest) (*CountWebGroupsResponse, error)
	GetWebGroup(context.Context, *GetWebGroupRequest) (*WebGroup, error)
	DeleteWebGroup(context.Context, *DeleteWebGroupRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWebGroupServiceServer()
}

// UnimplementedWebGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebGroupServiceServer struct{}

func (UnimplementedWebGroupServiceServer) CreateWebGroup(context.Context, *CreateWebGroupRequest) (*WebGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebGroup not implemented")
}
func (UnimplementedWebGroupServiceServer) UpdateWebGroup(context.Context, *UpdateWebGroupRequest) (*WebGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWebGroup not implemented")
}
func (UnimplementedWebGroupServiceServer) ListWebGroups(context.Context, *ListWebGroupsRequest) (*ListWebGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebGroups not implemented")
}
func (UnimplementedWebGroupServiceServer) CountWebGroups(context.Context, *CountWebGroupsRequest) (*CountWebGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountWebGroups not implemented")
}
func (UnimplementedWebGroupServiceServer) GetWebGroup(context.Context, *GetWebGroupRequest) (*WebGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebGroup not implemented")
}
func (UnimplementedWebGroupServiceServer) DeleteWebGroup(context.Context, *DeleteWebGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebGroup not implemented")
}
func (UnimplementedWebGroupServiceServer) mustEmbedUnimplementedWebGroupServiceServer() {}
func (UnimplementedWebGroupServiceServer) testEmbeddedByValue()                         {}

// UnsafeWebGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebGroupServiceServer will
// result in compilation errors.
type UnsafeWebGroupServiceServer interface {
	mustEmbedUnimplementedWebGroupServiceServer()
}

func RegisterWebGroupServiceServer(s grpc.ServiceRegistrar, srv WebGroupServiceServer) {
	// If the following call panics, it indicates UnimplementedWebGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebGroupService_ServiceDesc, srv)
}

func _WebGroupService_CreateWebGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).CreateWebGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_CreateWebGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).CreateWebGroup(ctx, req.(*CreateWebGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebGroupService_UpdateWebGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).UpdateWebGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_UpdateWebGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).UpdateWebGroup(ctx, req.(*UpdateWebGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebGroupService_ListWebGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).ListWebGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_ListWebGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).ListWebGroups(ctx, req.(*ListWebGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebGroupService_CountWebGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountWebGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).CountWebGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_CountWebGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).CountWebGroups(ctx, req.(*CountWebGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebGroupService_GetWebGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).GetWebGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_GetWebGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).GetWebGroup(ctx, req.(*GetWebGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebGroupService_DeleteWebGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebGroupServiceServer).DeleteWebGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebGroupService_DeleteWebGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebGroupServiceServer).DeleteWebGroup(ctx, req.(*DeleteWebGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebGroupService_ServiceDesc is the grpc.ServiceDesc for WebGroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebGroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.config.v1alpha.WebGroupService",
	HandlerType: (*WebGroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebGroup",
			Handler:    _WebGroupService_CreateWebGroup_Handler,
		},
		{
			MethodName: "UpdateWebGroup",
			Handler:    _WebGroupService_UpdateWebGroup_Handler,
		},
		{
			MethodName: "ListWebGroups",
			Handler:    _WebGroupService_ListWebGroups_Handler,
		},
		{
			MethodName: "CountWebGroups",
			Handler:    _WebGroupService_CountWebGroups_Handler,
		},
		{
			MethodName: "GetWebGroup",
			Handler:    _WebGroupService_GetWebGroup_Handler,
		},
		{
			MethodName: "DeleteWebGroup",
			Handler:    _WebGroupService_DeleteWebGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aviatrix/config/v1alpha/web_group_service_gen.proto",
}
