// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/cloud_account.proto
// generatedFile: aviatrix/config/v1alpha/cloud_account_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CloudAccountModel struct {
	Fabric            types.String `tfsdk:"fabric"`
	Name              types.String `tfsdk:"name"`
	DisplayName       types.String `tfsdk:"display_name"`
	Tags              types.Map    `tfsdk:"tags"`
	Aws               types.Object `tfsdk:"aws"`
	Gcp               types.Object `tfsdk:"gcp"`
	Azure             types.Object `tfsdk:"azure"`
	CloudOrganization types.String `tfsdk:"cloud_organization"`
	Tier              types.String `tfsdk:"tier"`
}

type AWSAccountDetails struct {
	AccountNumber  types.String `tfsdk:"account_number"`
	TokenInfo      types.Object `tfsdk:"token_info"`
	Credentials    types.Object `tfsdk:"credentials"`
	OnboardingMode types.String `tfsdk:"onboarding_mode"`
	Delegated      types.Object `tfsdk:"delegated"`
}

type AWSAccountDetailsDelegatedOnboarding struct {
	DelegatedRequestId types.String `tfsdk:"delegated_request_id"`
	ConsoleLink        types.String `tfsdk:"console_link"`
	ApprovalState      types.String `tfsdk:"approval_state"`
	Message            types.String `tfsdk:"message"`
}

type AWSAccountDetailsInlineCredentials struct {
	AccessId types.String `tfsdk:"access_id"`
	Secret   types.String `tfsdk:"secret"`
}

type AWSAccountDetailsTokenInfo struct {
	AssumedRoleArn types.String `tfsdk:"assumed_role_arn"`
}

type AzureAccountDetails struct {
	SubscriptionId types.String `tfsdk:"subscription_id"`
	DirectoryId    types.String `tfsdk:"directory_id"`
	ApplicationId  types.String `tfsdk:"application_id"`
	Credentials    types.Object `tfsdk:"credentials"`
}

type AzureAccountDetailsInlineCredentials struct {
	ApplicationKey types.String `tfsdk:"application_key"`
}

type GCPAccountDetails struct {
	ProjectId   types.String `tfsdk:"project_id"`
	Credentials types.Object `tfsdk:"credentials"`
}

type GCPAccountDetailsInlineCredentials struct {
	CredentialJson types.String `tfsdk:"credential_json"`
}

func AWSAccountDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"account_number": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"token_info": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  AWSAccountDetailsTokenInfoAttributes(),
		},
		"credentials": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  AWSAccountDetailsInlineCredentialsAttributes(),
		},
		"onboarding_mode": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"ONBOARDING_MODE_DELEGATED",
				),
			},
		},
		"delegated": schema.SingleNestedAttribute{
			Description: "",
			Computed:    true,
			Attributes:  AWSAccountDetailsDelegatedOnboardingAttributes(),
		},
	}
}
func AWSAccountDetailsDelegatedOnboardingAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"delegated_request_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"console_link": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"approval_state": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"APPROVAL_STATE_STARTED",
					"APPROVAL_STATE_IN_PROGRESS",
					"APPROVAL_STATE_ACCEPTED",
					"APPROVAL_STATE_REJECTED",
					"APPROVAL_STATE_ERROR",
				),
			},
		},
		"message": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}
}
func AWSAccountDetailsInlineCredentialsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"access_id": schema.StringAttribute{
			Description: "",
			Required:    true,
			Sensitive:   true,
		},
		"secret": schema.StringAttribute{
			Description: "",
			Required:    true,
			Sensitive:   true,
		},
	}
}
func AWSAccountDetailsTokenInfoAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"assumed_role_arn": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}
}
func AzureAccountDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"subscription_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"directory_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"application_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"credentials": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  AzureAccountDetailsInlineCredentialsAttributes(),
		},
	}
}
func AzureAccountDetailsInlineCredentialsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"application_key": schema.StringAttribute{
			Description: "",
			Required:    true,
			Sensitive:   true,
		},
	}
}
func GCPAccountDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"project_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"credentials": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  GCPAccountDetailsInlineCredentialsAttributes(),
		},
	}
}
func GCPAccountDetailsInlineCredentialsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"credential_json": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}
}

func CloudAccountSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Optional:    true,
			},
			"tags": schema.MapAttribute{
				Description: "",
				Optional:    true,
				ElementType: types.StringType,
			},
			"aws": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  AWSAccountDetailsAttributes(),
			},
			"gcp": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  GCPAccountDetailsAttributes(),
			},
			"azure": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  AzureAccountDetailsAttributes(),
			},
			"cloud_organization": schema.StringAttribute{
				Description: "",
				Computed:    true,
			},
			"tier": schema.StringAttribute{
				Description: "",
				Required:    true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"CLOUD_ACCOUNT_TIER_READ_ONLY",
						"CLOUD_ACCOUNT_TIER_PROTECTION",
					),
				},
			},
		},
	}
}
