// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/cloud_account.proto
// generatedFile: aviatrix/config/v1alpha/cloud_account_resource_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"fmt"
	"errors"
	"time"

	"buf.build/go/protovalidate"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"github.com/AviatrixSystems/terraform-provider-avxcloud/internal/tfresource"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CloudAccountResource{}
var _ resource.ResourceWithImportState = &CloudAccountResource{}

type CloudAccountClientGetter interface {
	CloudAccountClient() configpb.CloudAccountServiceClient
}

func NewCloudAccountResource() resource.Resource {
	return &CloudAccountResource{}
}

// CloudAccountResource defines the resource implementation.
type CloudAccountResource struct {
	client    configpb.CloudAccountServiceClient
	validator protovalidate.Validator
	// Parsed timeout and poll interval values
	createTimeout time.Duration
	updateTimeout time.Duration
	deleteTimeout time.Duration
	pollInterval  time.Duration
}

func (r *CloudAccountResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cloud_account"
}

func (r *CloudAccountResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = CloudAccountSchema()
}

func (r *CloudAccountResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	clients, ok := req.ProviderData.(CloudAccountClientGetter)
	if !ok {
		resp.Diagnostics.AddError(
			"unexpected ProviderData type",
			fmt.Sprintf("Expected CloudAccountClientGetter, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = clients.CloudAccountClient()

	// Initialize protovalidate validator
	validator, err := protovalidate.New()
	if err != nil {
		resp.Diagnostics.AddError(
			"protovalidate initialization failed",
			fmt.Sprintf("Please report this issue to the provider developers: %s", err),
		)
		return
	}
	r.validator = validator

	// Default timeout and poll interval configuration
	const (
		defaultCreateTimeout = "5m0s"
		defaultUpdateTimeout = "5m0s"
		defaultDeleteTimeout = "5m0s"
		defaultPollInterval  = "5s"
	)

	// Parse timeout and poll interval configuration
	r.createTimeout, err = time.ParseDuration(defaultCreateTimeout)
	if err != nil {
		resp.Diagnostics.AddError(
			"invalid create timeout configuration",
			fmt.Sprintf("Failed to parse create timeout %q: %s", defaultCreateTimeout, err),
		)
		return
	}
	r.updateTimeout, err = time.ParseDuration(defaultUpdateTimeout)
	if err != nil {
		resp.Diagnostics.AddError(
			"invalid update timeout configuration",
			fmt.Sprintf("Failed to parse update timeout %q: %s", defaultUpdateTimeout, err),
		)
		return
	}
	r.deleteTimeout, err = time.ParseDuration(defaultDeleteTimeout)
	if err != nil {
		resp.Diagnostics.AddError(
			"invalid delete timeout configuration",
			fmt.Sprintf("Failed to parse delete timeout %q: %s", defaultDeleteTimeout, err),
		)
		return
	}
	r.pollInterval, err = time.ParseDuration(defaultPollInterval)
	if err != nil {
		resp.Diagnostics.AddError(
			"invalid poll interval configuration",
			fmt.Sprintf("Failed to parse poll interval %q: %s", defaultPollInterval, err),
		)
		return
	}
}

func (r *CloudAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CloudAccountModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiReq := data.ToCreateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate the request before calling the API
	if err := r.validator.Validate(apiReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	result, err := r.client.CreateCloudAccount(ctx, apiReq)
	if err != nil {
		resp.Diagnostics.AddError("create failed", err.Error())
		return
	}

	// Wait for resource to become ready and get final state
	waitResult, err := r.waitForReady(ctx, result.Name, r.createTimeout)
	if err != nil {
		resp.Diagnostics.AddError("failed waiting for ready state", err.Error())
	}
	if waitResult != nil {
		result = waitResult
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)

	// Save data into Terraform state
	resp.Diagnostics.Append(tfresource.SetGeneration(ctx, resp.Private, result.GetGeneration())...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CloudAccountModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call the API
	result, err := r.client.GetCloudAccount(ctx, &configpb.GetCloudAccountRequest{
		Name: data.Name.ValueString(),
	})
	if err != nil {
		status, ok := status.FromError(err)
		if ok && status.Code() == codes.NotFound {
			tflog.Info(ctx, fmt.Sprintf("CloudAccount %s not found, removing from state", data.Name.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(fmt.Sprintf("failed to read cloud_account %s", data.Name.ValueString()), err.Error())
		return
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(tfresource.SetGeneration(ctx, resp.Private, result.GetGeneration())...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CloudAccountModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert to update request
	updateReq := data.ToUpdateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get generation from private state
	gen, diags := tfresource.GetGeneration(ctx, resp.Private)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	updateReq.CloudAccount.Generation = gen

	// Validate the request before calling the API
	if err := r.validator.Validate(updateReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	result, err := r.client.UpdateCloudAccount(ctx, updateReq)
	if err != nil {
		resp.Diagnostics.AddError("update failed", err.Error())
		return
	}

	// Wait for resource to become ready and get final state
	waitResult, err := r.waitForReady(ctx, result.Name, r.updateTimeout)
	if err != nil {
		resp.Diagnostics.AddError("failed waiting for ready state", err.Error())
	}
	if waitResult != nil {
		result = waitResult
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(tfresource.SetGeneration(ctx, resp.Private, result.GetGeneration())...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CloudAccountModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create delete request
	deleteReq := &configpb.DeleteCloudAccountRequest{
		Name: data.Name.ValueString(),
	}

	// Validate the request before calling the API
	if err := r.validator.Validate(deleteReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	_, err := r.client.DeleteCloudAccount(ctx, deleteReq)
	if err != nil {
		resp.Diagnostics.AddError("delete failed", err.Error())
		return
	}

	// Wait for resource to be deleted
	if err := r.waitForDeleted(ctx, deleteReq.Name); err != nil {
		resp.Diagnostics.AddError("failed waiting for deleted state", err.Error())
		return
	}
}

func (r *CloudAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}

// waitForReady waits for the resource to reach READY state after create or update.
// Returns the final resource state.
func (r *CloudAccountResource) waitForReady(ctx context.Context, name string, timeout time.Duration) (*configpb.CloudAccount, error) {
	stateConf := &retry.StateChangeConf{
		Pending: []string{configpb.ResourceState_RESOURCE_STATE_RECONCILING.String()},
		Target:  []string{configpb.ResourceState_RESOURCE_STATE_READY.String()},
		Refresh: func() (interface{}, string, error) {
			result, err := r.client.GetCloudAccount(ctx, &configpb.GetCloudAccountRequest{
				Name: name,
			})
			if err != nil {
				return nil, "", err
			}
			status := result.GetStatus()
			state := status.GetResourceState()
			if state == configpb.ResourceState_RESOURCE_STATE_ERROR {
				return result, state.String(), errors.New(status.GetMessage())
			}
			return result, state.String(), nil
		},
		Timeout:      timeout,
		PollInterval: r.pollInterval,
	}
	obj, err := stateConf.WaitForStateContext(ctx)
	result, ok := obj.(*configpb.CloudAccount)
	if !ok && err == nil {
		return nil, fmt.Errorf("unexpected type from state refresh: %T", obj)
	}
	return result, err
}

// waitForDeleted waits for the resource to reach DELETED state after delete.
func (r *CloudAccountResource) waitForDeleted(ctx context.Context, name string) error {
	stateConf := &retry.StateChangeConf{
		Pending: []string{
			configpb.ResourceState_RESOURCE_STATE_DELETING.String(),
			configpb.ResourceState_RESOURCE_STATE_READY.String(),
		},
		Target: []string{configpb.ResourceState_RESOURCE_STATE_DELETED.String()},
		Refresh: func() (interface{}, string, error) {
			result, err := r.client.GetCloudAccount(ctx, &configpb.GetCloudAccountRequest{
				Name: name,
			})
			if status.Code(err) == codes.NotFound {
				return struct{}{}, configpb.ResourceState_RESOURCE_STATE_DELETED.String(), nil
			} else if err != nil {
				return nil, "", err
			}
			state := result.GetStatus().GetResourceState()
			return struct{}{}, state.String(), nil
		},
		Timeout:      r.deleteTimeout,
		PollInterval: r.pollInterval,
	}
	_, err := stateConf.WaitForStateContext(ctx)
	return err
}
