// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/cloud_account.proto
// generatedFile: aviatrix/config/v1alpha/cloud_account_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"fmt"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	"github.com/AviatrixSystems/terraform-provider-avxcloud/internal/tfresource"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a CloudAccountModel to a configpb.CloudAccount message
func (m *CloudAccountModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.CloudAccount {
	if m == nil {
		return nil
	}

	proto := &configpb.CloudAccount{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// Map field: Tags
	if !m.Tags.IsNull() && !m.Tags.IsUnknown() {
		elements := make(map[string]types.String, len(m.Tags.Elements()))
		diags.Append(m.Tags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Tags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Tags[k] = v.ValueString()
				}
			}
		}
	}
	// Oneof object field: Aws
	if !m.Aws.IsNull() && !m.Aws.IsUnknown() {
		var intermediate AWSAccountDetails
		diags.Append(m.Aws.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudAccount = &configpb.CloudAccount_Aws{
				Aws: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Gcp
	if !m.Gcp.IsNull() && !m.Gcp.IsUnknown() {
		var intermediate GCPAccountDetails
		diags.Append(m.Gcp.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudAccount = &configpb.CloudAccount_Gcp{
				Gcp: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Azure
	if !m.Azure.IsNull() && !m.Azure.IsUnknown() {
		var intermediate AzureAccountDetails
		diags.Append(m.Azure.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudAccount = &configpb.CloudAccount_Azure{
				Azure: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Enum field: Tier
	if !m.Tier.IsNull() && !m.Tier.IsUnknown() {
		proto.Tier = configpb.CloudAccountTier(configpb.CloudAccountTier_value[m.Tier.ValueString()])
	}

	return proto
}

// ToCreateRequest converts a CloudAccountModel to a CreateCloudAccountRequest
func (m *CloudAccountModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateCloudAccountRequest {
	if m == nil {
		return nil
	}

	// Generate resource ID
	prefix := tfresource.GetResourcePrefix("CloudAccount")
	id, err := tfresource.GenerateResourceID(prefix)
	if err != nil {
		diags.AddError("ID Generation Error", fmt.Sprintf("Failed to generate resource ID: %s", err))
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}
	// Set the full resource name
	resource.Name = fmt.Sprintf("%s/cloudAccounts/%s", parent, id)

	return &configpb.CreateCloudAccountRequest{
		Parent:         parent,
		CloudAccount:   resource,
		CloudAccountId: id,
	}
}

// ToUpdateRequest converts a CloudAccountModel to an UpdateCloudAccountRequest
func (m *CloudAccountModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateCloudAccountRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateCloudAccountRequest{
		CloudAccount: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a CloudAccountModel from a configpb.CloudAccount message
func (m *CloudAccountModel) FromProto(ctx context.Context, proto *configpb.CloudAccount, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/cloudAccounts/cloudAccount-abc"
	m.Fabric = extractParentCloudAccountString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// Map field: Tags
	if len(proto.Tags) > 0 {
		elements := make(map[string]types.String, len(proto.Tags))
		for k, v := range proto.Tags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Tags = mapValue
	} else if !m.Tags.IsNull() {
		m.Tags = types.MapNull(types.StringType)
	}
	// Object: Aws
	if proto.GetAws() != nil {
		var intermediate AWSAccountDetails
		intermediate.FromProto(ctx, proto.GetAws(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AWSAccountDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Aws = objValue
	} else {
		m.Aws = types.ObjectNull(AWSAccountDetailsAttrTypes())
	}
	// Object: Gcp
	if proto.GetGcp() != nil {
		var intermediate GCPAccountDetails
		intermediate.FromProto(ctx, proto.GetGcp(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, GCPAccountDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Gcp = objValue
	} else {
		m.Gcp = types.ObjectNull(GCPAccountDetailsAttrTypes())
	}
	// Object: Azure
	if proto.GetAzure() != nil {
		var intermediate AzureAccountDetails
		intermediate.FromProto(ctx, proto.GetAzure(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AzureAccountDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Azure = objValue
	} else {
		m.Azure = types.ObjectNull(AzureAccountDetailsAttrTypes())
	}
	// String field: CloudOrganization
	if proto.GetCloudOrganization() != "" {
		m.CloudOrganization = types.StringValue(proto.GetCloudOrganization())
	} else {
		m.CloudOrganization = types.StringValue("")
	}
	// Enum field: Tier
	if proto.GetTier() != 0 {
		m.Tier = types.StringValue(proto.GetTier().String())
	} else if !m.Tier.IsNull() {
		m.Tier = types.StringNull()
	}
}

// ToProto converts a AWSAccountDetails to a configpb.AWSAccountDetails message
func (m *AWSAccountDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AWSAccountDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.AWSAccountDetails{}
	// String field: AccountNumber
	if !m.AccountNumber.IsNull() && !m.AccountNumber.IsUnknown() {
		proto.AccountNumber = m.AccountNumber.ValueString()
	}
	// Oneof object field: TokenInfo
	if !m.TokenInfo.IsNull() && !m.TokenInfo.IsUnknown() {
		var intermediate AWSAccountDetailsTokenInfo
		diags.Append(m.TokenInfo.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Credential = &configpb.AWSAccountDetails_TokenInfo_{
				TokenInfo: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Credentials
	if !m.Credentials.IsNull() && !m.Credentials.IsUnknown() {
		var intermediate AWSAccountDetailsInlineCredentials
		diags.Append(m.Credentials.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Credential = &configpb.AWSAccountDetails_Credentials{
				Credentials: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof enum field: OnboardingMode
	if !m.OnboardingMode.IsNull() && !m.OnboardingMode.IsUnknown() {
		proto.Credential = &configpb.AWSAccountDetails_OnboardingMode_{
			OnboardingMode: configpb.AWSAccountDetails_OnboardingMode(configpb.AWSAccountDetails_OnboardingMode_value[m.OnboardingMode.ValueString()]),
		}
	}
	// Object: Delegated
	if !m.Delegated.IsNull() && !m.Delegated.IsUnknown() {
		var intermediate AWSAccountDetailsDelegatedOnboarding
		diags.Append(m.Delegated.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Delegated = intermediate.ToProto(ctx, diags)
		}
	}

	return proto
}

// FromProto populates a AWSAccountDetails from a configpb.AWSAccountDetails message
func (m *AWSAccountDetails) FromProto(ctx context.Context, proto *configpb.AWSAccountDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: AccountNumber
	if proto.GetAccountNumber() != "" {
		m.AccountNumber = types.StringValue(proto.GetAccountNumber())
	} else if !m.AccountNumber.IsNull() {
		m.AccountNumber = types.StringValue("")
	}
	// Object: TokenInfo
	if proto.GetTokenInfo() != nil {
		var intermediate AWSAccountDetailsTokenInfo
		intermediate.FromProto(ctx, proto.GetTokenInfo(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AWSAccountDetailsTokenInfoAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.TokenInfo = objValue
	} else {
		m.TokenInfo = types.ObjectNull(AWSAccountDetailsTokenInfoAttrTypes())
	}
	// Object: Credentials
	if proto.GetCredentials() != nil {
		var intermediate AWSAccountDetailsInlineCredentials
		intermediate.FromProto(ctx, proto.GetCredentials(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AWSAccountDetailsInlineCredentialsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Credentials = objValue
	} else {
		m.Credentials = types.ObjectNull(AWSAccountDetailsInlineCredentialsAttrTypes())
	}
	// Enum field: OnboardingMode
	if proto.GetOnboardingMode() != 0 {
		m.OnboardingMode = types.StringValue(proto.GetOnboardingMode().String())
	} else if !m.OnboardingMode.IsNull() {
		m.OnboardingMode = types.StringNull()
	}
	// Object: Delegated
	if proto.GetDelegated() != nil {
		var intermediate AWSAccountDetailsDelegatedOnboarding
		intermediate.FromProto(ctx, proto.GetDelegated(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AWSAccountDetailsDelegatedOnboardingAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Delegated = objValue
	} else {
		m.Delegated = types.ObjectNull(AWSAccountDetailsDelegatedOnboardingAttrTypes())
	}
}

// ToProto converts a AWSAccountDetailsDelegatedOnboarding to a configpb.AWSAccountDetails_DelegatedOnboarding message
func (m *AWSAccountDetailsDelegatedOnboarding) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AWSAccountDetails_DelegatedOnboarding {
	if m == nil {
		return nil
	}

	proto := &configpb.AWSAccountDetails_DelegatedOnboarding{}
	// String field: DelegatedRequestId
	if !m.DelegatedRequestId.IsNull() && !m.DelegatedRequestId.IsUnknown() {
		proto.DelegatedRequestId = m.DelegatedRequestId.ValueString()
	}
	// String field: ConsoleLink
	if !m.ConsoleLink.IsNull() && !m.ConsoleLink.IsUnknown() {
		proto.ConsoleLink = m.ConsoleLink.ValueString()
	}
	// Enum field: ApprovalState
	if !m.ApprovalState.IsNull() && !m.ApprovalState.IsUnknown() {
		proto.ApprovalState = configpb.AWSAccountDetails_DelegatedOnboarding_ApprovalState(configpb.AWSAccountDetails_DelegatedOnboarding_ApprovalState_value[m.ApprovalState.ValueString()])
	}
	// String field: Message
	if !m.Message.IsNull() && !m.Message.IsUnknown() {
		proto.Message = m.Message.ValueString()
	}

	return proto
}

// FromProto populates a AWSAccountDetailsDelegatedOnboarding from a configpb.AWSAccountDetails_DelegatedOnboarding message
func (m *AWSAccountDetailsDelegatedOnboarding) FromProto(ctx context.Context, proto *configpb.AWSAccountDetails_DelegatedOnboarding, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: DelegatedRequestId
	if proto.GetDelegatedRequestId() != "" {
		m.DelegatedRequestId = types.StringValue(proto.GetDelegatedRequestId())
	} else if !m.DelegatedRequestId.IsNull() {
		m.DelegatedRequestId = types.StringValue("")
	}
	// String field: ConsoleLink
	if proto.GetConsoleLink() != "" {
		m.ConsoleLink = types.StringValue(proto.GetConsoleLink())
	} else if !m.ConsoleLink.IsNull() {
		m.ConsoleLink = types.StringValue("")
	}
	// Enum field: ApprovalState
	if proto.GetApprovalState() != 0 {
		m.ApprovalState = types.StringValue(proto.GetApprovalState().String())
	} else if !m.ApprovalState.IsNull() {
		m.ApprovalState = types.StringNull()
	}
	// String field: Message
	if proto.GetMessage() != "" {
		m.Message = types.StringValue(proto.GetMessage())
	} else if !m.Message.IsNull() {
		m.Message = types.StringValue("")
	}
}

// ToProto converts a AWSAccountDetailsInlineCredentials to a configpb.AWSAccountDetails_InlineCredentials message
func (m *AWSAccountDetailsInlineCredentials) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AWSAccountDetails_InlineCredentials {
	if m == nil {
		return nil
	}

	proto := &configpb.AWSAccountDetails_InlineCredentials{}
	// String field: AccessId
	if !m.AccessId.IsNull() && !m.AccessId.IsUnknown() {
		proto.AccessId = m.AccessId.ValueString()
	}
	// String field: Secret
	if !m.Secret.IsNull() && !m.Secret.IsUnknown() {
		proto.Secret = m.Secret.ValueString()
	}

	return proto
}

// FromProto populates a AWSAccountDetailsInlineCredentials from a configpb.AWSAccountDetails_InlineCredentials message
func (m *AWSAccountDetailsInlineCredentials) FromProto(ctx context.Context, proto *configpb.AWSAccountDetails_InlineCredentials, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: AccessId
	if proto.GetAccessId() != "" {
		m.AccessId = types.StringValue(proto.GetAccessId())
	} else if !m.AccessId.IsNull() {
		m.AccessId = types.StringValue("")
	}
	// String field: Secret
	if proto.GetSecret() != "" {
		m.Secret = types.StringValue(proto.GetSecret())
	} else if !m.Secret.IsNull() {
		m.Secret = types.StringValue("")
	}
}

// ToProto converts a AWSAccountDetailsTokenInfo to a configpb.AWSAccountDetails_TokenInfo message
func (m *AWSAccountDetailsTokenInfo) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AWSAccountDetails_TokenInfo {
	if m == nil {
		return nil
	}

	proto := &configpb.AWSAccountDetails_TokenInfo{}
	// String field: AssumedRoleArn
	if !m.AssumedRoleArn.IsNull() && !m.AssumedRoleArn.IsUnknown() {
		proto.AssumedRoleArn = m.AssumedRoleArn.ValueString()
	}

	return proto
}

// FromProto populates a AWSAccountDetailsTokenInfo from a configpb.AWSAccountDetails_TokenInfo message
func (m *AWSAccountDetailsTokenInfo) FromProto(ctx context.Context, proto *configpb.AWSAccountDetails_TokenInfo, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: AssumedRoleArn
	if proto.GetAssumedRoleArn() != "" {
		m.AssumedRoleArn = types.StringValue(proto.GetAssumedRoleArn())
	} else if !m.AssumedRoleArn.IsNull() {
		m.AssumedRoleArn = types.StringValue("")
	}
}

// ToProto converts a AzureAccountDetails to a configpb.AzureAccountDetails message
func (m *AzureAccountDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AzureAccountDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.AzureAccountDetails{}
	// String field: SubscriptionId
	if !m.SubscriptionId.IsNull() && !m.SubscriptionId.IsUnknown() {
		proto.SubscriptionId = m.SubscriptionId.ValueString()
	}
	// String field: DirectoryId
	if !m.DirectoryId.IsNull() && !m.DirectoryId.IsUnknown() {
		proto.DirectoryId = m.DirectoryId.ValueString()
	}
	// String field: ApplicationId
	if !m.ApplicationId.IsNull() && !m.ApplicationId.IsUnknown() {
		proto.ApplicationId = m.ApplicationId.ValueString()
	}
	// Oneof object field: Credentials
	if !m.Credentials.IsNull() && !m.Credentials.IsUnknown() {
		var intermediate AzureAccountDetailsInlineCredentials
		diags.Append(m.Credentials.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Credential = &configpb.AzureAccountDetails_Credentials{
				Credentials: intermediate.ToProto(ctx, diags),
			}
		}
	}

	return proto
}

// FromProto populates a AzureAccountDetails from a configpb.AzureAccountDetails message
func (m *AzureAccountDetails) FromProto(ctx context.Context, proto *configpb.AzureAccountDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: SubscriptionId
	if proto.GetSubscriptionId() != "" {
		m.SubscriptionId = types.StringValue(proto.GetSubscriptionId())
	} else if !m.SubscriptionId.IsNull() {
		m.SubscriptionId = types.StringValue("")
	}
	// String field: DirectoryId
	if proto.GetDirectoryId() != "" {
		m.DirectoryId = types.StringValue(proto.GetDirectoryId())
	} else if !m.DirectoryId.IsNull() {
		m.DirectoryId = types.StringValue("")
	}
	// String field: ApplicationId
	if proto.GetApplicationId() != "" {
		m.ApplicationId = types.StringValue(proto.GetApplicationId())
	} else if !m.ApplicationId.IsNull() {
		m.ApplicationId = types.StringValue("")
	}
	// Object: Credentials
	if proto.GetCredentials() != nil {
		var intermediate AzureAccountDetailsInlineCredentials
		intermediate.FromProto(ctx, proto.GetCredentials(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, AzureAccountDetailsInlineCredentialsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Credentials = objValue
	} else {
		m.Credentials = types.ObjectNull(AzureAccountDetailsInlineCredentialsAttrTypes())
	}
}

// ToProto converts a AzureAccountDetailsInlineCredentials to a configpb.AzureAccountDetails_InlineCredentials message
func (m *AzureAccountDetailsInlineCredentials) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.AzureAccountDetails_InlineCredentials {
	if m == nil {
		return nil
	}

	proto := &configpb.AzureAccountDetails_InlineCredentials{}
	// String field: ApplicationKey
	if !m.ApplicationKey.IsNull() && !m.ApplicationKey.IsUnknown() {
		proto.ApplicationKey = m.ApplicationKey.ValueString()
	}

	return proto
}

// FromProto populates a AzureAccountDetailsInlineCredentials from a configpb.AzureAccountDetails_InlineCredentials message
func (m *AzureAccountDetailsInlineCredentials) FromProto(ctx context.Context, proto *configpb.AzureAccountDetails_InlineCredentials, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: ApplicationKey
	if proto.GetApplicationKey() != "" {
		m.ApplicationKey = types.StringValue(proto.GetApplicationKey())
	} else if !m.ApplicationKey.IsNull() {
		m.ApplicationKey = types.StringValue("")
	}
}

// ToProto converts a GCPAccountDetails to a configpb.GCPAccountDetails message
func (m *GCPAccountDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.GCPAccountDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.GCPAccountDetails{}
	// String field: ProjectId
	if !m.ProjectId.IsNull() && !m.ProjectId.IsUnknown() {
		proto.ProjectId = m.ProjectId.ValueString()
	}
	// Oneof object field: Credentials
	if !m.Credentials.IsNull() && !m.Credentials.IsUnknown() {
		var intermediate GCPAccountDetailsInlineCredentials
		diags.Append(m.Credentials.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Credential = &configpb.GCPAccountDetails_Credentials{
				Credentials: intermediate.ToProto(ctx, diags),
			}
		}
	}

	return proto
}

// FromProto populates a GCPAccountDetails from a configpb.GCPAccountDetails message
func (m *GCPAccountDetails) FromProto(ctx context.Context, proto *configpb.GCPAccountDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: ProjectId
	if proto.GetProjectId() != "" {
		m.ProjectId = types.StringValue(proto.GetProjectId())
	} else if !m.ProjectId.IsNull() {
		m.ProjectId = types.StringValue("")
	}
	// Object: Credentials
	if proto.GetCredentials() != nil {
		var intermediate GCPAccountDetailsInlineCredentials
		intermediate.FromProto(ctx, proto.GetCredentials(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, GCPAccountDetailsInlineCredentialsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Credentials = objValue
	} else {
		m.Credentials = types.ObjectNull(GCPAccountDetailsInlineCredentialsAttrTypes())
	}
}

// ToProto converts a GCPAccountDetailsInlineCredentials to a configpb.GCPAccountDetails_InlineCredentials message
func (m *GCPAccountDetailsInlineCredentials) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.GCPAccountDetails_InlineCredentials {
	if m == nil {
		return nil
	}

	proto := &configpb.GCPAccountDetails_InlineCredentials{}
	// String field: CredentialJson
	if !m.CredentialJson.IsNull() && !m.CredentialJson.IsUnknown() {
		proto.CredentialJson = m.CredentialJson.ValueString()
	}

	return proto
}

// FromProto populates a GCPAccountDetailsInlineCredentials from a configpb.GCPAccountDetails_InlineCredentials message
func (m *GCPAccountDetailsInlineCredentials) FromProto(ctx context.Context, proto *configpb.GCPAccountDetails_InlineCredentials, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: CredentialJson
	if proto.GetCredentialJson() != "" {
		m.CredentialJson = types.StringValue(proto.GetCredentialJson())
	} else if !m.CredentialJson.IsNull() {
		m.CredentialJson = types.StringValue("")
	}
}

// AWSAccountDetailsAttrTypes returns the attribute types for AWSAccountDetails
func AWSAccountDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"account_number":  types.StringType,
		"token_info":      types.ObjectType{AttrTypes: AWSAccountDetailsTokenInfoAttrTypes()},
		"credentials":     types.ObjectType{AttrTypes: AWSAccountDetailsInlineCredentialsAttrTypes()},
		"onboarding_mode": types.StringType,
		"delegated":       types.ObjectType{AttrTypes: AWSAccountDetailsDelegatedOnboardingAttrTypes()},
	}
}

// AWSAccountDetailsDelegatedOnboardingAttrTypes returns the attribute types for AWSAccountDetailsDelegatedOnboarding
func AWSAccountDetailsDelegatedOnboardingAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"delegated_request_id": types.StringType,
		"console_link":         types.StringType,
		"approval_state":       types.StringType,
		"message":              types.StringType,
	}
}

// AWSAccountDetailsInlineCredentialsAttrTypes returns the attribute types for AWSAccountDetailsInlineCredentials
func AWSAccountDetailsInlineCredentialsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"access_id": types.StringType,
		"secret":    types.StringType,
	}
}

// AWSAccountDetailsTokenInfoAttrTypes returns the attribute types for AWSAccountDetailsTokenInfo
func AWSAccountDetailsTokenInfoAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"assumed_role_arn": types.StringType,
	}
}

// AzureAccountDetailsAttrTypes returns the attribute types for AzureAccountDetails
func AzureAccountDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"subscription_id": types.StringType,
		"directory_id":    types.StringType,
		"application_id":  types.StringType,
		"credentials":     types.ObjectType{AttrTypes: AzureAccountDetailsInlineCredentialsAttrTypes()},
	}
}

// AzureAccountDetailsInlineCredentialsAttrTypes returns the attribute types for AzureAccountDetailsInlineCredentials
func AzureAccountDetailsInlineCredentialsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"application_key": types.StringType,
	}
}

// GCPAccountDetailsAttrTypes returns the attribute types for GCPAccountDetails
func GCPAccountDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"project_id":  types.StringType,
		"credentials": types.ObjectType{AttrTypes: GCPAccountDetailsInlineCredentialsAttrTypes()},
	}
}

// GCPAccountDetailsInlineCredentialsAttrTypes returns the attribute types for GCPAccountDetailsInlineCredentials
func GCPAccountDetailsInlineCredentialsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"credential_json": types.StringType,
	}
}

// extractParentCloudAccountString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/cloudAccounts/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentCloudAccountString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/cloudAccounts/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
