// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_list.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_list_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DcfPolicyListModel struct {
	Fabric              types.String `tfsdk:"fabric"`
	Name                types.String `tfsdk:"name"`
	DisplayName         types.String `tfsdk:"display_name"`
	Policies            types.List   `tfsdk:"policies"`
	AttachmentPointUuid types.String `tfsdk:"attachment_point_uuid"`
	SystemResource      types.Bool   `tfsdk:"system_resource"`
}

type DcfPolicyListPolicy struct {
	DisplayName        types.String `tfsdk:"display_name"`
	Uuid               types.String `tfsdk:"uuid"`
	Priority           types.Int64  `tfsdk:"priority"`
	Action             types.String `tfsdk:"action"`
	Protocol           types.String `tfsdk:"protocol"`
	SrcGroups          types.List   `tfsdk:"src_groups"`
	DstGroups          types.List   `tfsdk:"dst_groups"`
	WebGroups          types.List   `tfsdk:"web_groups"`
	PortRanges         types.List   `tfsdk:"port_ranges"`
	Logging            types.Bool   `tfsdk:"logging"`
	Watch              types.Bool   `tfsdk:"watch"`
	FlowAppRequirement types.String `tfsdk:"flow_app_requirement"`
	DecryptPolicy      types.String `tfsdk:"decrypt_policy"`
	IntrusionSeverity  types.String `tfsdk:"intrusion_severity"`
	SystemResource     types.Bool   `tfsdk:"system_resource"`
}

type DcfPolicyListPolicyPortRange struct {
	Low  types.Int64 `tfsdk:"low"`
	High types.Int64 `tfsdk:"high"`
}

func DcfPolicyListPolicyAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"display_name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"uuid": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseNonNullStateForUnknown(),
			},
		},
		"priority": schema.Int64Attribute{
			Description: "",
			Required:    true,
		},
		"action": schema.StringAttribute{
			Description: "",
			Required:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"ACTION_PERMIT",
					"ACTION_DENY",
					"ACTION_CONTINUE",
					"ACTION_INTRUSION_DETECTION_PERMIT",
					"ACTION_INTRUSION_DETECTION_CONTINUE",
					"ACTION_INTRUSION_PREVENTION_PERMIT",
					"ACTION_INTRUSION_PREVENTION_CONTINUE",
				),
			},
		},
		"protocol": schema.StringAttribute{
			Description: "",
			Required:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"PROTOCOL_TCP",
					"PROTOCOL_UDP",
					"PROTOCOL_ICMP",
				),
			},
		},
		"src_groups": schema.ListAttribute{
			Description: "",
			Required:    true,
			ElementType: types.StringType,
		},
		"dst_groups": schema.ListAttribute{
			Description: "",
			Required:    true,
			ElementType: types.StringType,
		},
		"web_groups": schema.ListAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
		"port_ranges": schema.ListNestedAttribute{
			Description: "",
			Optional:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: DcfPolicyListPolicyPortRangeAttributes(),
			},
		},
		"logging": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"watch": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"flow_app_requirement": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"FLOW_APP_REQUIREMENT_TLS_REQUIRED",
					"FLOW_APP_REQUIREMENT_NOT_TLS_REQUIRED",
				),
			},
		},
		"decrypt_policy": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"DECRYPT_POLICY_ALLOWED",
					"DECRYPT_POLICY_NOT_ALLOWED",
				),
			},
		},
		"intrusion_severity": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"INTRUSION_SEVERITY_CRITICAL",
					"INTRUSION_SEVERITY_MAJOR",
					"INTRUSION_SEVERITY_MINOR",
					"INTRUSION_SEVERITY_INFORMATIONAL",
					"INTRUSION_SEVERITY_ALL",
				),
			},
		},
		"system_resource": schema.BoolAttribute{
			Description: "",
			Computed:    true,
		},
	}
}
func DcfPolicyListPolicyPortRangeAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"low": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"high": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
	}
}

func DcfPolicyListSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Required:    true,
			},
			"policies": schema.ListNestedAttribute{
				Description: "",
				Required:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: DcfPolicyListPolicyAttributes(),
				},
			},
			"attachment_point_uuid": schema.StringAttribute{
				Description: "",
				Optional:    true,
			},
			"system_resource": schema.BoolAttribute{
				Description: "",
				Computed:    true,
			},
		},
	}
}
