// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_list.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_list_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a DcfPolicyListModel to a configpb.DcfPolicyList message
func (m *DcfPolicyListModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyList {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyList{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// List field: Policies
	if !m.Policies.IsNull() && !m.Policies.IsUnknown() {
		var intermediates []DcfPolicyListPolicy
		diags.Append(m.Policies.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Policies = append(proto.Policies, item.ToProto(ctx, diags))
			}
		}
	}
	// String field: AttachmentPointUuid
	if !m.AttachmentPointUuid.IsNull() && !m.AttachmentPointUuid.IsUnknown() {
		proto.AttachmentPointUuid = m.AttachmentPointUuid.ValueString()
	}

	return proto
}

// ToCreateRequest converts a DcfPolicyListModel to a CreateDcfPolicyListRequest
func (m *DcfPolicyListModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateDcfPolicyListRequest {
	if m == nil {
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.CreateDcfPolicyListRequest{
		Parent:        parent,
		DcfPolicyList: resource,
	}
}

// ToUpdateRequest converts a DcfPolicyListModel to an UpdateDcfPolicyListRequest
func (m *DcfPolicyListModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateDcfPolicyListRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateDcfPolicyListRequest{
		DcfPolicyList: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a DcfPolicyListModel from a configpb.DcfPolicyList message
func (m *DcfPolicyListModel) FromProto(ctx context.Context, proto *configpb.DcfPolicyList, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/dcfPolicyLists/dcfPolicyList-abc"
	m.Fabric = extractParentDcfPolicyListString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// List field: Policies
	if len(proto.Policies) > 0 {
		// List of objects
		intermediates := make([]DcfPolicyListPolicy, len(proto.Policies))
		for i, item := range proto.Policies {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: DcfPolicyListPolicyAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Policies = listValue
	} else {
		m.Policies = types.ListNull(types.ObjectType{AttrTypes: DcfPolicyListPolicyAttrTypes()})
	}
	// String field: AttachmentPointUuid
	if proto.GetAttachmentPointUuid() != "" {
		m.AttachmentPointUuid = types.StringValue(proto.GetAttachmentPointUuid())
	} else if !m.AttachmentPointUuid.IsNull() {
		m.AttachmentPointUuid = types.StringValue("")
	}
	// Bool field: SystemResource
	if proto.GetSystemResource() != false {
		m.SystemResource = types.BoolValue(proto.GetSystemResource())
	} else {
		m.SystemResource = types.BoolValue(false)
	}
}

// ToProto converts a DcfPolicyListPolicy to a configpb.DcfPolicyList_Policy message
func (m *DcfPolicyListPolicy) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyList_Policy {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyList_Policy{}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// String field: Uuid
	if !m.Uuid.IsNull() && !m.Uuid.IsUnknown() {
		proto.Uuid = m.Uuid.ValueString()
	}
	// Int field: Priority
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		proto.Priority = int32(m.Priority.ValueInt64())
	}
	// Enum field: Action
	if !m.Action.IsNull() && !m.Action.IsUnknown() {
		proto.Action = configpb.DcfPolicyList_Policy_Action(configpb.DcfPolicyList_Policy_Action_value[m.Action.ValueString()])
	}
	// Enum field: Protocol
	if !m.Protocol.IsNull() && !m.Protocol.IsUnknown() {
		proto.Protocol = configpb.DcfPolicyList_Policy_Protocol(configpb.DcfPolicyList_Policy_Protocol_value[m.Protocol.ValueString()])
	}
	// List field: SrcGroups
	if !m.SrcGroups.IsNull() && !m.SrcGroups.IsUnknown() {
		var elements []types.String
		diags.Append(m.SrcGroups.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() && len(elements) > 0 {

			proto.SrcGroups = make([]string, len(elements))
			for i, v := range elements {
				proto.SrcGroups[i] = v.ValueString()
			}
		}
	}
	// List field: DstGroups
	if !m.DstGroups.IsNull() && !m.DstGroups.IsUnknown() {
		var elements []types.String
		diags.Append(m.DstGroups.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() && len(elements) > 0 {

			proto.DstGroups = make([]string, len(elements))
			for i, v := range elements {
				proto.DstGroups[i] = v.ValueString()
			}
		}
	}
	// List field: WebGroups
	if !m.WebGroups.IsNull() && !m.WebGroups.IsUnknown() {
		var elements []types.String
		diags.Append(m.WebGroups.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() && len(elements) > 0 {

			proto.WebGroups = make([]string, len(elements))
			for i, v := range elements {
				proto.WebGroups[i] = v.ValueString()
			}
		}
	}
	// List field: PortRanges
	if !m.PortRanges.IsNull() && !m.PortRanges.IsUnknown() {
		var intermediates []DcfPolicyListPolicyPortRange
		diags.Append(m.PortRanges.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.PortRanges = append(proto.PortRanges, item.ToProto(ctx, diags))
			}
		}
	}
	// Bool field: Logging
	if !m.Logging.IsNull() && !m.Logging.IsUnknown() {
		proto.Logging = m.Logging.ValueBool()
	}
	// Bool field: Watch
	if !m.Watch.IsNull() && !m.Watch.IsUnknown() {
		proto.Watch = m.Watch.ValueBool()
	}
	// Enum field: FlowAppRequirement
	if !m.FlowAppRequirement.IsNull() && !m.FlowAppRequirement.IsUnknown() {
		proto.FlowAppRequirement = configpb.DcfPolicyList_Policy_FlowAppRequirement(configpb.DcfPolicyList_Policy_FlowAppRequirement_value[m.FlowAppRequirement.ValueString()])
	}
	// Enum field: DecryptPolicy
	if !m.DecryptPolicy.IsNull() && !m.DecryptPolicy.IsUnknown() {
		proto.DecryptPolicy = configpb.DcfPolicyList_Policy_DecryptPolicy(configpb.DcfPolicyList_Policy_DecryptPolicy_value[m.DecryptPolicy.ValueString()])
	}
	// Enum field: IntrusionSeverity
	if !m.IntrusionSeverity.IsNull() && !m.IntrusionSeverity.IsUnknown() {
		proto.IntrusionSeverity = configpb.DcfPolicyList_Policy_IntrusionSeverity(configpb.DcfPolicyList_Policy_IntrusionSeverity_value[m.IntrusionSeverity.ValueString()])
	}
	// Bool field: SystemResource
	if !m.SystemResource.IsNull() && !m.SystemResource.IsUnknown() {
		proto.SystemResource = m.SystemResource.ValueBool()
	}

	return proto
}

// FromProto populates a DcfPolicyListPolicy from a configpb.DcfPolicyList_Policy message
func (m *DcfPolicyListPolicy) FromProto(ctx context.Context, proto *configpb.DcfPolicyList_Policy, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// String field: Uuid
	if proto.GetUuid() != "" {
		m.Uuid = types.StringValue(proto.GetUuid())
	} else {
		m.Uuid = types.StringValue("")
	}
	// Int field: Priority
	if proto.GetPriority() != 0 {
		m.Priority = types.Int64Value(int64(proto.GetPriority()))
	} else if !m.Priority.IsNull() {
		m.Priority = types.Int64Value(0)
	}
	// Enum field: Action
	if proto.GetAction() != 0 {
		m.Action = types.StringValue(proto.GetAction().String())
	} else if !m.Action.IsNull() {
		m.Action = types.StringNull()
	}
	// Enum field: Protocol
	if proto.GetProtocol() != 0 {
		m.Protocol = types.StringValue(proto.GetProtocol().String())
	} else if !m.Protocol.IsNull() {
		m.Protocol = types.StringNull()
	}
	// List field: SrcGroups
	if len(proto.SrcGroups) > 0 {
		elements := make([]types.String, len(proto.SrcGroups))
		for i, v := range proto.SrcGroups {
			elements[i] = types.StringValue(v)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.StringType, elements)
		diags.Append(listDiags...)
		m.SrcGroups = listValue
	} else {
		m.SrcGroups = types.ListNull(types.StringType)
	}
	// List field: DstGroups
	if len(proto.DstGroups) > 0 {
		elements := make([]types.String, len(proto.DstGroups))
		for i, v := range proto.DstGroups {
			elements[i] = types.StringValue(v)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.StringType, elements)
		diags.Append(listDiags...)
		m.DstGroups = listValue
	} else {
		m.DstGroups = types.ListNull(types.StringType)
	}
	// List field: WebGroups
	if len(proto.WebGroups) > 0 {
		elements := make([]types.String, len(proto.WebGroups))
		for i, v := range proto.WebGroups {
			elements[i] = types.StringValue(v)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.StringType, elements)
		diags.Append(listDiags...)
		m.WebGroups = listValue
	} else {
		m.WebGroups = types.ListNull(types.StringType)
	}
	// List field: PortRanges
	if len(proto.PortRanges) > 0 {
		// List of objects
		intermediates := make([]DcfPolicyListPolicyPortRange, len(proto.PortRanges))
		for i, item := range proto.PortRanges {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: DcfPolicyListPolicyPortRangeAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.PortRanges = listValue
	} else {
		m.PortRanges = types.ListNull(types.ObjectType{AttrTypes: DcfPolicyListPolicyPortRangeAttrTypes()})
	}
	// Bool field: Logging
	if proto.GetLogging() != false {
		m.Logging = types.BoolValue(proto.GetLogging())
	} else if !m.Logging.IsNull() {
		m.Logging = types.BoolValue(false)
	}
	// Bool field: Watch
	if proto.GetWatch() != false {
		m.Watch = types.BoolValue(proto.GetWatch())
	} else if !m.Watch.IsNull() {
		m.Watch = types.BoolValue(false)
	}
	// Enum field: FlowAppRequirement
	if proto.GetFlowAppRequirement() != 0 {
		m.FlowAppRequirement = types.StringValue(proto.GetFlowAppRequirement().String())
	} else if !m.FlowAppRequirement.IsNull() {
		m.FlowAppRequirement = types.StringNull()
	}
	// Enum field: DecryptPolicy
	if proto.GetDecryptPolicy() != 0 {
		m.DecryptPolicy = types.StringValue(proto.GetDecryptPolicy().String())
	} else if !m.DecryptPolicy.IsNull() {
		m.DecryptPolicy = types.StringNull()
	}
	// Enum field: IntrusionSeverity
	if proto.GetIntrusionSeverity() != 0 {
		m.IntrusionSeverity = types.StringValue(proto.GetIntrusionSeverity().String())
	} else if !m.IntrusionSeverity.IsNull() {
		m.IntrusionSeverity = types.StringNull()
	}
	// Bool field: SystemResource
	if proto.GetSystemResource() != false {
		m.SystemResource = types.BoolValue(proto.GetSystemResource())
	} else {
		m.SystemResource = types.BoolValue(false)
	}
}

// ToProto converts a DcfPolicyListPolicyPortRange to a configpb.DcfPolicyList_Policy_PortRange message
func (m *DcfPolicyListPolicyPortRange) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyList_Policy_PortRange {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyList_Policy_PortRange{}
	// Int field: Low
	if !m.Low.IsNull() && !m.Low.IsUnknown() {
		proto.Low = uint32(m.Low.ValueInt64())
	}
	// Int field: High
	if !m.High.IsNull() && !m.High.IsUnknown() {
		proto.High = uint32(m.High.ValueInt64())
	}

	return proto
}

// FromProto populates a DcfPolicyListPolicyPortRange from a configpb.DcfPolicyList_Policy_PortRange message
func (m *DcfPolicyListPolicyPortRange) FromProto(ctx context.Context, proto *configpb.DcfPolicyList_Policy_PortRange, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Int field: Low
	if proto.GetLow() != 0 {
		m.Low = types.Int64Value(int64(proto.GetLow()))
	} else if !m.Low.IsNull() {
		m.Low = types.Int64Value(0)
	}
	// Int field: High
	if proto.GetHigh() != 0 {
		m.High = types.Int64Value(int64(proto.GetHigh()))
	} else if !m.High.IsNull() {
		m.High = types.Int64Value(0)
	}
}

// DcfPolicyListPolicyAttrTypes returns the attribute types for DcfPolicyListPolicy
func DcfPolicyListPolicyAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"display_name":         types.StringType,
		"uuid":                 types.StringType,
		"priority":             types.Int64Type,
		"action":               types.StringType,
		"protocol":             types.StringType,
		"src_groups":           types.ListType{ElemType: types.StringType},
		"dst_groups":           types.ListType{ElemType: types.StringType},
		"web_groups":           types.ListType{ElemType: types.StringType},
		"port_ranges":          types.ListType{ElemType: types.ObjectType{AttrTypes: DcfPolicyListPolicyPortRangeAttrTypes()}},
		"logging":              types.BoolType,
		"watch":                types.BoolType,
		"flow_app_requirement": types.StringType,
		"decrypt_policy":       types.StringType,
		"intrusion_severity":   types.StringType,
		"system_resource":      types.BoolType,
	}
}

// DcfPolicyListPolicyPortRangeAttrTypes returns the attribute types for DcfPolicyListPolicyPortRange
func DcfPolicyListPolicyPortRangeAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"low":  types.Int64Type,
		"high": types.Int64Type,
	}
}

// extractParentDcfPolicyListString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/dcfPolicyLists/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentDcfPolicyListString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/dcfPolicyLists/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
