// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_block.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_block_resource_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"fmt"

	"buf.build/go/protovalidate"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DcfPolicyBlockResource{}
var _ resource.ResourceWithImportState = &DcfPolicyBlockResource{}

type DcfPolicyBlockClientGetter interface {
	DcfPolicyBlockClient() configpb.DcfPolicyBlockServiceClient
}

func NewDcfPolicyBlockResource() resource.Resource {
	return &DcfPolicyBlockResource{}
}

// DcfPolicyBlockResource defines the resource implementation.
type DcfPolicyBlockResource struct {
	client    configpb.DcfPolicyBlockServiceClient
	validator protovalidate.Validator
}

func (r *DcfPolicyBlockResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dcf_policy_block"
}

func (r *DcfPolicyBlockResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = DcfPolicyBlockSchema()
}

func (r *DcfPolicyBlockResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	clients, ok := req.ProviderData.(DcfPolicyBlockClientGetter)
	if !ok {
		resp.Diagnostics.AddError(
			"unexpected ProviderData type",
			fmt.Sprintf("Expected DcfPolicyBlockClientGetter, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = clients.DcfPolicyBlockClient()

	// Initialize protovalidate validator
	validator, err := protovalidate.New()
	if err != nil {
		resp.Diagnostics.AddError(
			"protovalidate initialization failed",
			fmt.Sprintf("Please report this issue to the provider developers: %s", err),
		)
		return
	}
	r.validator = validator
}

func (r *DcfPolicyBlockResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data DcfPolicyBlockModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiReq := data.ToCreateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate the request before calling the API
	if err := r.validator.Validate(apiReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	result, err := r.client.CreateDcfPolicyBlock(ctx, apiReq)
	if err != nil {
		resp.Diagnostics.AddError("create failed", err.Error())
		return
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DcfPolicyBlockResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data DcfPolicyBlockModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call the API
	result, err := r.client.GetDcfPolicyBlock(ctx, &configpb.GetDcfPolicyBlockRequest{
		Name: data.Name.ValueString(),
	})
	if err != nil {
		status, ok := status.FromError(err)
		if ok && status.Code() == codes.NotFound {
			tflog.Info(ctx, fmt.Sprintf("DcfPolicyBlock %s not found, removing from state", data.Name.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(fmt.Sprintf("failed to read dcf_policy_block %s", data.Name.ValueString()), err.Error())
		return
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DcfPolicyBlockResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data DcfPolicyBlockModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert to update request
	updateReq := data.ToUpdateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate the request before calling the API
	if err := r.validator.Validate(updateReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	result, err := r.client.UpdateDcfPolicyBlock(ctx, updateReq)
	if err != nil {
		resp.Diagnostics.AddError("update failed", err.Error())
		return
	}

	// Update the model with the result
	data.FromProto(ctx, result, &resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DcfPolicyBlockResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data DcfPolicyBlockModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create delete request
	deleteReq := &configpb.DeleteDcfPolicyBlockRequest{
		Name: data.Name.ValueString(),
	}

	// Validate the request before calling the API
	if err := r.validator.Validate(deleteReq); err != nil {
		resp.Diagnostics.AddError("validation failed", err.Error())
		return
	}

	// Call the API
	_, err := r.client.DeleteDcfPolicyBlock(ctx, deleteReq)
	if err != nil {
		resp.Diagnostics.AddError("delete failed", err.Error())
		return
	}
}

func (r *DcfPolicyBlockResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
