// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_block.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_block_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a DcfPolicyBlockModel to a configpb.DcfPolicyBlock message
func (m *DcfPolicyBlockModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyBlock {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyBlock{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// List field: SubPolicies
	if !m.SubPolicies.IsNull() && !m.SubPolicies.IsUnknown() {
		var intermediates []DcfPolicyBlockSubPolicy
		diags.Append(m.SubPolicies.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.SubPolicies = append(proto.SubPolicies, item.ToProto(ctx, diags))
			}
		}
	}
	// String field: AttachmentPointUuid
	if !m.AttachmentPointUuid.IsNull() && !m.AttachmentPointUuid.IsUnknown() {
		proto.AttachmentPointUuid = m.AttachmentPointUuid.ValueString()
	}

	return proto
}

// ToCreateRequest converts a DcfPolicyBlockModel to a CreateDcfPolicyBlockRequest
func (m *DcfPolicyBlockModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateDcfPolicyBlockRequest {
	if m == nil {
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.CreateDcfPolicyBlockRequest{
		Parent:         parent,
		DcfPolicyBlock: resource,
	}
}

// ToUpdateRequest converts a DcfPolicyBlockModel to an UpdateDcfPolicyBlockRequest
func (m *DcfPolicyBlockModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateDcfPolicyBlockRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateDcfPolicyBlockRequest{
		DcfPolicyBlock: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a DcfPolicyBlockModel from a configpb.DcfPolicyBlock message
func (m *DcfPolicyBlockModel) FromProto(ctx context.Context, proto *configpb.DcfPolicyBlock, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/dcfPolicyBlocks/dcfPolicyBlock-abc"
	m.Fabric = extractParentDcfPolicyBlockString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// List field: SubPolicies
	if len(proto.SubPolicies) > 0 {
		// List of objects
		intermediates := make([]DcfPolicyBlockSubPolicy, len(proto.SubPolicies))
		for i, item := range proto.SubPolicies {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: DcfPolicyBlockSubPolicyAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.SubPolicies = listValue
	} else {
		m.SubPolicies = types.ListNull(types.ObjectType{AttrTypes: DcfPolicyBlockSubPolicyAttrTypes()})
	}
	// String field: AttachmentPointUuid
	if proto.GetAttachmentPointUuid() != "" {
		m.AttachmentPointUuid = types.StringValue(proto.GetAttachmentPointUuid())
	} else if !m.AttachmentPointUuid.IsNull() {
		m.AttachmentPointUuid = types.StringValue("")
	}
	// Bool field: SystemResource
	if proto.GetSystemResource() != false {
		m.SystemResource = types.BoolValue(proto.GetSystemResource())
	} else {
		m.SystemResource = types.BoolValue(false)
	}
}

// ToProto converts a DcfPolicyBlockSubPolicy to a configpb.DcfPolicyBlock_SubPolicy message
func (m *DcfPolicyBlockSubPolicy) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyBlock_SubPolicy {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyBlock_SubPolicy{}
	// Oneof object field: PolicyBlock
	if !m.PolicyBlock.IsNull() && !m.PolicyBlock.IsUnknown() {
		var intermediate DcfPolicyBlockSubPolicyBlock
		diags.Append(m.PolicyBlock.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.SubPolicy = &configpb.DcfPolicyBlock_SubPolicy_PolicyBlock{
				PolicyBlock: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: PolicyList
	if !m.PolicyList.IsNull() && !m.PolicyList.IsUnknown() {
		var intermediate DcfPolicyBlockSubPolicyList
		diags.Append(m.PolicyList.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.SubPolicy = &configpb.DcfPolicyBlock_SubPolicy_PolicyList{
				PolicyList: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: AttachmentPoint
	if !m.AttachmentPoint.IsNull() && !m.AttachmentPoint.IsUnknown() {
		var intermediate DcfPolicyBlockSubPolicyAttachmentPoint
		diags.Append(m.AttachmentPoint.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.SubPolicy = &configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint_{
				AttachmentPoint: intermediate.ToProto(ctx, diags),
			}
		}
	}

	return proto
}

// FromProto populates a DcfPolicyBlockSubPolicy from a configpb.DcfPolicyBlock_SubPolicy message
func (m *DcfPolicyBlockSubPolicy) FromProto(ctx context.Context, proto *configpb.DcfPolicyBlock_SubPolicy, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Object: PolicyBlock
	if proto.GetPolicyBlock() != nil {
		var intermediate DcfPolicyBlockSubPolicyBlock
		intermediate.FromProto(ctx, proto.GetPolicyBlock(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, DcfPolicyBlockSubPolicyBlockAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.PolicyBlock = objValue
	} else {
		m.PolicyBlock = types.ObjectNull(DcfPolicyBlockSubPolicyBlockAttrTypes())
	}
	// Object: PolicyList
	if proto.GetPolicyList() != nil {
		var intermediate DcfPolicyBlockSubPolicyList
		intermediate.FromProto(ctx, proto.GetPolicyList(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, DcfPolicyBlockSubPolicyListAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.PolicyList = objValue
	} else {
		m.PolicyList = types.ObjectNull(DcfPolicyBlockSubPolicyListAttrTypes())
	}
	// Object: AttachmentPoint
	if proto.GetAttachmentPoint() != nil {
		var intermediate DcfPolicyBlockSubPolicyAttachmentPoint
		intermediate.FromProto(ctx, proto.GetAttachmentPoint(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, DcfPolicyBlockSubPolicyAttachmentPointAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.AttachmentPoint = objValue
	} else {
		m.AttachmentPoint = types.ObjectNull(DcfPolicyBlockSubPolicyAttachmentPointAttrTypes())
	}
}

// ToProto converts a DcfPolicyBlockSubPolicyAttachmentPoint to a configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint message
func (m *DcfPolicyBlockSubPolicyAttachmentPoint) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint{}
	// Int field: Priority
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		proto.Priority = uint32(m.Priority.ValueInt64())
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// String field: Uuid
	if !m.Uuid.IsNull() && !m.Uuid.IsUnknown() {
		proto.Uuid = m.Uuid.ValueString()
	}
	// String field: Target
	if !m.Target.IsNull() && !m.Target.IsUnknown() {
		proto.Target = m.Target.ValueString()
	}

	return proto
}

// FromProto populates a DcfPolicyBlockSubPolicyAttachmentPoint from a configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint message
func (m *DcfPolicyBlockSubPolicyAttachmentPoint) FromProto(ctx context.Context, proto *configpb.DcfPolicyBlock_SubPolicy_AttachmentPoint, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Int field: Priority
	if proto.GetPriority() != 0 {
		m.Priority = types.Int64Value(int64(proto.GetPriority()))
	} else if !m.Priority.IsNull() {
		m.Priority = types.Int64Value(0)
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// String field: Uuid
	if proto.GetUuid() != "" {
		m.Uuid = types.StringValue(proto.GetUuid())
	} else {
		m.Uuid = types.StringValue("")
	}
	// String field: Target
	if proto.GetTarget() != "" {
		m.Target = types.StringValue(proto.GetTarget())
	} else {
		m.Target = types.StringValue("")
	}
}

// ToProto converts a DcfPolicyBlockSubPolicyBlock to a configpb.DcfPolicyBlock_SubPolicy_Block message
func (m *DcfPolicyBlockSubPolicyBlock) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyBlock_SubPolicy_Block {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyBlock_SubPolicy_Block{}
	// Int field: Priority
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		proto.Priority = uint32(m.Priority.ValueInt64())
	}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}

	return proto
}

// FromProto populates a DcfPolicyBlockSubPolicyBlock from a configpb.DcfPolicyBlock_SubPolicy_Block message
func (m *DcfPolicyBlockSubPolicyBlock) FromProto(ctx context.Context, proto *configpb.DcfPolicyBlock_SubPolicy_Block, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Int field: Priority
	if proto.GetPriority() != 0 {
		m.Priority = types.Int64Value(int64(proto.GetPriority()))
	} else if !m.Priority.IsNull() {
		m.Priority = types.Int64Value(0)
	}
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else if !m.Name.IsNull() {
		m.Name = types.StringValue("")
	}
}

// ToProto converts a DcfPolicyBlockSubPolicyList to a configpb.DcfPolicyBlock_SubPolicy_List message
func (m *DcfPolicyBlockSubPolicyList) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.DcfPolicyBlock_SubPolicy_List {
	if m == nil {
		return nil
	}

	proto := &configpb.DcfPolicyBlock_SubPolicy_List{}
	// Int field: Priority
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		proto.Priority = uint32(m.Priority.ValueInt64())
	}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}

	return proto
}

// FromProto populates a DcfPolicyBlockSubPolicyList from a configpb.DcfPolicyBlock_SubPolicy_List message
func (m *DcfPolicyBlockSubPolicyList) FromProto(ctx context.Context, proto *configpb.DcfPolicyBlock_SubPolicy_List, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Int field: Priority
	if proto.GetPriority() != 0 {
		m.Priority = types.Int64Value(int64(proto.GetPriority()))
	} else if !m.Priority.IsNull() {
		m.Priority = types.Int64Value(0)
	}
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else if !m.Name.IsNull() {
		m.Name = types.StringValue("")
	}
}

// DcfPolicyBlockSubPolicyAttrTypes returns the attribute types for DcfPolicyBlockSubPolicy
func DcfPolicyBlockSubPolicyAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"policy_block":     types.ObjectType{AttrTypes: DcfPolicyBlockSubPolicyBlockAttrTypes()},
		"policy_list":      types.ObjectType{AttrTypes: DcfPolicyBlockSubPolicyListAttrTypes()},
		"attachment_point": types.ObjectType{AttrTypes: DcfPolicyBlockSubPolicyAttachmentPointAttrTypes()},
	}
}

// DcfPolicyBlockSubPolicyAttachmentPointAttrTypes returns the attribute types for DcfPolicyBlockSubPolicyAttachmentPoint
func DcfPolicyBlockSubPolicyAttachmentPointAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"priority":     types.Int64Type,
		"display_name": types.StringType,
		"uuid":         types.StringType,
		"target":       types.StringType,
	}
}

// DcfPolicyBlockSubPolicyBlockAttrTypes returns the attribute types for DcfPolicyBlockSubPolicyBlock
func DcfPolicyBlockSubPolicyBlockAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"priority": types.Int64Type,
		"name":     types.StringType,
	}
}

// DcfPolicyBlockSubPolicyListAttrTypes returns the attribute types for DcfPolicyBlockSubPolicyList
func DcfPolicyBlockSubPolicyListAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"priority": types.Int64Type,
		"name":     types.StringType,
	}
}

// extractParentDcfPolicyBlockString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/dcfPolicyBlocks/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentDcfPolicyBlockString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/dcfPolicyBlocks/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
