// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/dcf_policy_block.proto
// generatedFile: aviatrix/config/v1alpha/dcf_policy_block_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DcfPolicyBlockModel struct {
	Fabric              types.String `tfsdk:"fabric"`
	Name                types.String `tfsdk:"name"`
	DisplayName         types.String `tfsdk:"display_name"`
	SubPolicies         types.List   `tfsdk:"sub_policies"`
	AttachmentPointUuid types.String `tfsdk:"attachment_point_uuid"`
	SystemResource      types.Bool   `tfsdk:"system_resource"`
}

type DcfPolicyBlockSubPolicy struct {
	PolicyBlock     types.Object `tfsdk:"policy_block"`
	PolicyList      types.Object `tfsdk:"policy_list"`
	AttachmentPoint types.Object `tfsdk:"attachment_point"`
}

type DcfPolicyBlockSubPolicyAttachmentPoint struct {
	Priority    types.Int64  `tfsdk:"priority"`
	DisplayName types.String `tfsdk:"display_name"`
	Uuid        types.String `tfsdk:"uuid"`
	Target      types.String `tfsdk:"target"`
}

type DcfPolicyBlockSubPolicyBlock struct {
	Priority types.Int64  `tfsdk:"priority"`
	Name     types.String `tfsdk:"name"`
}

type DcfPolicyBlockSubPolicyList struct {
	Priority types.Int64  `tfsdk:"priority"`
	Name     types.String `tfsdk:"name"`
}

func DcfPolicyBlockSubPolicyAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"policy_block": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  DcfPolicyBlockSubPolicyBlockAttributes(),
		},
		"policy_list": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  DcfPolicyBlockSubPolicyListAttributes(),
		},
		"attachment_point": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  DcfPolicyBlockSubPolicyAttachmentPointAttributes(),
		},
	}
}
func DcfPolicyBlockSubPolicyAttachmentPointAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"priority": schema.Int64Attribute{
			Description: "",
			Required:    true,
		},
		"display_name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"uuid": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseNonNullStateForUnknown(),
			},
		},
		"target": schema.StringAttribute{
			Description: "",
			Computed:    true,
		},
	}
}
func DcfPolicyBlockSubPolicyBlockAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"priority": schema.Int64Attribute{
			Description: "",
			Required:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}
}
func DcfPolicyBlockSubPolicyListAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"priority": schema.Int64Attribute{
			Description: "",
			Required:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}
}

func DcfPolicyBlockSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Required:    true,
			},
			"sub_policies": schema.ListNestedAttribute{
				Description: "",
				Required:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: DcfPolicyBlockSubPolicyAttributes(),
				},
			},
			"attachment_point_uuid": schema.StringAttribute{
				Description: "",
				Optional:    true,
			},
			"system_resource": schema.BoolAttribute{
				Description: "",
				Computed:    true,
			},
		},
	}
}
