// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/network.proto
// generatedFile: aviatrix/config/v1alpha/network_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NetworkModel struct {
	Fabric            types.String `tfsdk:"fabric"`
	Name              types.String `tfsdk:"name"`
	DisplayName       types.String `tfsdk:"display_name"`
	Tags              types.Map    `tfsdk:"tags"`
	CloudResourceTags types.Map    `tfsdk:"cloud_resource_tags"`
	PerformanceClass  types.String `tfsdk:"performance_class"`
	Aws               types.Object `tfsdk:"aws"`
	Gcp               types.Object `tfsdk:"gcp"`
	Azure             types.Object `tfsdk:"azure"`
	CloudAccount      types.String `tfsdk:"cloud_account"`
}

type NetworkAWSDetails struct {
	VpcId   types.String `tfsdk:"vpc_id"`
	Subnets types.List   `tfsdk:"subnets"`
}

type NetworkAWSDetailsSubnet struct {
	PublicSubnetId types.String `tfsdk:"public_subnet_id"`
	Eip            types.String `tfsdk:"eip"`
}

type NetworkAzureDetails struct {
	VnetId  types.String `tfsdk:"vnet_id"`
	Subnets types.List   `tfsdk:"subnets"`
}

type NetworkAzureDetailsSubnet struct {
	PublicSubnetId   types.String `tfsdk:"public_subnet_id"`
	AvailabilityZone types.String `tfsdk:"availability_zone"`
}

type NetworkGCPDetails struct {
	VpcId   types.String `tfsdk:"vpc_id"`
	Subnets types.List   `tfsdk:"subnets"`
}

type NetworkGCPDetailsSubnet struct {
	PublicSubnetId   types.String `tfsdk:"public_subnet_id"`
	AvailabilityZone types.String `tfsdk:"availability_zone"`
}

func NetworkAWSDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"vpc_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"subnets": schema.ListNestedAttribute{
			Description: "",
			Required:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: NetworkAWSDetailsSubnetAttributes(),
			},
		},
	}
}
func NetworkAWSDetailsSubnetAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"public_subnet_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"eip": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}
}
func NetworkAzureDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"vnet_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"subnets": schema.ListNestedAttribute{
			Description: "",
			Required:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: NetworkAzureDetailsSubnetAttributes(),
			},
		},
	}
}
func NetworkAzureDetailsSubnetAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"public_subnet_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"availability_zone": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}
}
func NetworkGCPDetailsAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"vpc_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"subnets": schema.ListNestedAttribute{
			Description: "",
			Required:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: NetworkGCPDetailsSubnetAttributes(),
			},
		},
	}
}
func NetworkGCPDetailsSubnetAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"public_subnet_id": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"availability_zone": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}
}

func NetworkSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Optional:    true,
			},
			"tags": schema.MapAttribute{
				Description: "",
				Optional:    true,
				ElementType: types.StringType,
			},
			"cloud_resource_tags": schema.MapAttribute{
				Description: "",
				Optional:    true,
				ElementType: types.StringType,
			},
			"performance_class": schema.StringAttribute{
				Description: "",
				Required:    true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"NETWORK_PERFORMANCE_CLASS_XSMALL",
						"NETWORK_PERFORMANCE_CLASS_SMALL",
						"NETWORK_PERFORMANCE_CLASS_MEDIUM",
						"NETWORK_PERFORMANCE_CLASS_LARGE",
						"NETWORK_PERFORMANCE_CLASS_XLARGE",
						"NETWORK_PERFORMANCE_CLASS_XXLARGE",
					),
				},
			},
			"aws": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  NetworkAWSDetailsAttributes(),
			},
			"gcp": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  NetworkGCPDetailsAttributes(),
			},
			"azure": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  NetworkAzureDetailsAttributes(),
			},
			"cloud_account": schema.StringAttribute{
				Description: "",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}
