// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/network_inspection.proto
// generatedFile: aviatrix/config/v1alpha/network_inspection_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"fmt"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	"github.com/AviatrixSystems/terraform-provider-avxcloud/internal/tfresource"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a NetworkInspectionModel to a configpb.NetworkInspection message
func (m *NetworkInspectionModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.NetworkInspection {
	if m == nil {
		return nil
	}

	proto := &configpb.NetworkInspection{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: Network
	if !m.Network.IsNull() && !m.Network.IsUnknown() {
		proto.Network = m.Network.ValueString()
	}
	// Object: Egress
	if !m.Egress.IsNull() && !m.Egress.IsUnknown() {
		var intermediate NetworkInspectionEgress
		diags.Append(m.Egress.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Egress = intermediate.ToProto(ctx, diags)
		}
	}
	// Oneof object field: AwsEastWest
	if !m.AwsEastWest.IsNull() && !m.AwsEastWest.IsUnknown() {
		var intermediate NetworkInspectionAwsEastWest
		diags.Append(m.AwsEastWest.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.EastWest = &configpb.NetworkInspection_AwsEastWest_{
				AwsEastWest: intermediate.ToProto(ctx, diags),
			}
		}
	}

	return proto
}

// ToCreateRequest converts a NetworkInspectionModel to a CreateNetworkInspectionRequest
func (m *NetworkInspectionModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateNetworkInspectionRequest {
	if m == nil {
		return nil
	}

	// Generate resource ID
	prefix := tfresource.GetResourcePrefix("NetworkInspection")
	id, err := tfresource.GenerateResourceID(prefix)
	if err != nil {
		diags.AddError("ID Generation Error", fmt.Sprintf("Failed to generate resource ID: %s", err))
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}
	// Set the full resource name
	resource.Name = fmt.Sprintf("%s/networkInspections/%s", parent, id)

	return &configpb.CreateNetworkInspectionRequest{
		Parent:              parent,
		NetworkInspection:   resource,
		NetworkInspectionId: id,
	}
}

// ToUpdateRequest converts a NetworkInspectionModel to an UpdateNetworkInspectionRequest
func (m *NetworkInspectionModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateNetworkInspectionRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateNetworkInspectionRequest{
		NetworkInspection: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a NetworkInspectionModel from a configpb.NetworkInspection message
func (m *NetworkInspectionModel) FromProto(ctx context.Context, proto *configpb.NetworkInspection, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/networkInspections/networkInspection-abc"
	m.Fabric = extractParentNetworkInspectionString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: Network
	if proto.GetNetwork() != "" {
		m.Network = types.StringValue(proto.GetNetwork())
	} else if !m.Network.IsNull() {
		m.Network = types.StringValue("")
	}
	// Object: Egress
	if proto.GetEgress() != nil {
		var intermediate NetworkInspectionEgress
		intermediate.FromProto(ctx, proto.GetEgress(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, NetworkInspectionEgressAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Egress = objValue
	} else {
		m.Egress = types.ObjectNull(NetworkInspectionEgressAttrTypes())
	}
	// Object: AwsEastWest
	if proto.GetAwsEastWest() != nil {
		var intermediate NetworkInspectionAwsEastWest
		intermediate.FromProto(ctx, proto.GetAwsEastWest(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, NetworkInspectionAwsEastWestAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.AwsEastWest = objValue
	} else {
		m.AwsEastWest = types.ObjectNull(NetworkInspectionAwsEastWestAttrTypes())
	}
}

// ToProto converts a NetworkInspectionAwsEastWest to a configpb.NetworkInspection_AwsEastWest message
func (m *NetworkInspectionAwsEastWest) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.NetworkInspection_AwsEastWest {
	if m == nil {
		return nil
	}

	proto := &configpb.NetworkInspection_AwsEastWest{}
	// Enum field: Scope
	if !m.Scope.IsNull() && !m.Scope.IsUnknown() {
		proto.Scope = configpb.NetworkInspection_AwsEastWest_Scope(configpb.NetworkInspection_AwsEastWest_Scope_value[m.Scope.ValueString()])
	}
	// List field: RouteTableIds
	if !m.RouteTableIds.IsNull() && !m.RouteTableIds.IsUnknown() {
		var elements []types.String
		diags.Append(m.RouteTableIds.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() && len(elements) > 0 {

			proto.RouteTableIds = make([]string, len(elements))
			for i, v := range elements {
				proto.RouteTableIds[i] = v.ValueString()
			}
		}
	}

	return proto
}

// FromProto populates a NetworkInspectionAwsEastWest from a configpb.NetworkInspection_AwsEastWest message
func (m *NetworkInspectionAwsEastWest) FromProto(ctx context.Context, proto *configpb.NetworkInspection_AwsEastWest, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Enum field: Scope
	if proto.GetScope() != 0 {
		m.Scope = types.StringValue(proto.GetScope().String())
	} else if !m.Scope.IsNull() {
		m.Scope = types.StringNull()
	}
	// List field: RouteTableIds
	if len(proto.RouteTableIds) > 0 {
		elements := make([]types.String, len(proto.RouteTableIds))
		for i, v := range proto.RouteTableIds {
			elements[i] = types.StringValue(v)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.StringType, elements)
		diags.Append(listDiags...)
		m.RouteTableIds = listValue
	} else {
		m.RouteTableIds = types.ListNull(types.StringType)
	}
}

// ToProto converts a NetworkInspectionEgress to a configpb.NetworkInspection_Egress message
func (m *NetworkInspectionEgress) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.NetworkInspection_Egress {
	if m == nil {
		return nil
	}

	proto := &configpb.NetworkInspection_Egress{}
	// Bool field: Enabled
	if !m.Enabled.IsNull() && !m.Enabled.IsUnknown() {
		proto.Enabled = m.Enabled.ValueBool()
	}
	// List field: PrivateRouteTableIds
	if !m.PrivateRouteTableIds.IsNull() && !m.PrivateRouteTableIds.IsUnknown() {
		var elements []types.String
		diags.Append(m.PrivateRouteTableIds.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() && len(elements) > 0 {

			proto.PrivateRouteTableIds = make([]string, len(elements))
			for i, v := range elements {
				proto.PrivateRouteTableIds[i] = v.ValueString()
			}
		}
	}

	return proto
}

// FromProto populates a NetworkInspectionEgress from a configpb.NetworkInspection_Egress message
func (m *NetworkInspectionEgress) FromProto(ctx context.Context, proto *configpb.NetworkInspection_Egress, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Bool field: Enabled
	if proto.GetEnabled() != false {
		m.Enabled = types.BoolValue(proto.GetEnabled())
	} else if !m.Enabled.IsNull() {
		m.Enabled = types.BoolValue(false)
	}
	// List field: PrivateRouteTableIds
	if len(proto.PrivateRouteTableIds) > 0 {
		elements := make([]types.String, len(proto.PrivateRouteTableIds))
		for i, v := range proto.PrivateRouteTableIds {
			elements[i] = types.StringValue(v)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.StringType, elements)
		diags.Append(listDiags...)
		m.PrivateRouteTableIds = listValue
	} else {
		m.PrivateRouteTableIds = types.ListNull(types.StringType)
	}
}

// NetworkInspectionAwsEastWestAttrTypes returns the attribute types for NetworkInspectionAwsEastWest
func NetworkInspectionAwsEastWestAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"scope":           types.StringType,
		"route_table_ids": types.ListType{ElemType: types.StringType},
	}
}

// NetworkInspectionEgressAttrTypes returns the attribute types for NetworkInspectionEgress
func NetworkInspectionEgressAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"enabled":                 types.BoolType,
		"private_route_table_ids": types.ListType{ElemType: types.StringType},
	}
}

// extractParentNetworkInspectionString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/networkInspections/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentNetworkInspectionString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/networkInspections/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
