// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/network.proto
// generatedFile: aviatrix/config/v1alpha/network_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"fmt"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	"github.com/AviatrixSystems/terraform-provider-avxcloud/internal/tfresource"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a NetworkModel to a configpb.Network message
func (m *NetworkModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network {
	if m == nil {
		return nil
	}

	proto := &configpb.Network{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// Map field: Tags
	if !m.Tags.IsNull() && !m.Tags.IsUnknown() {
		elements := make(map[string]types.String, len(m.Tags.Elements()))
		diags.Append(m.Tags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Tags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Tags[k] = v.ValueString()
				}
			}
		}
	}
	// Map field: CloudResourceTags
	if !m.CloudResourceTags.IsNull() && !m.CloudResourceTags.IsUnknown() {
		elements := make(map[string]types.String, len(m.CloudResourceTags.Elements()))
		diags.Append(m.CloudResourceTags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.CloudResourceTags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.CloudResourceTags[k] = v.ValueString()
				}
			}
		}
	}
	// Enum field: PerformanceClass
	if !m.PerformanceClass.IsNull() && !m.PerformanceClass.IsUnknown() {
		proto.PerformanceClass = configpb.Network_NetworkPerformanceClass(configpb.Network_NetworkPerformanceClass_value[m.PerformanceClass.ValueString()])
	}
	// Oneof object field: Aws
	if !m.Aws.IsNull() && !m.Aws.IsUnknown() {
		var intermediate NetworkAWSDetails
		diags.Append(m.Aws.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudNetwork = &configpb.Network_Aws{
				Aws: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Gcp
	if !m.Gcp.IsNull() && !m.Gcp.IsUnknown() {
		var intermediate NetworkGCPDetails
		diags.Append(m.Gcp.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudNetwork = &configpb.Network_Gcp{
				Gcp: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Azure
	if !m.Azure.IsNull() && !m.Azure.IsUnknown() {
		var intermediate NetworkAzureDetails
		diags.Append(m.Azure.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.CloudNetwork = &configpb.Network_Azure{
				Azure: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// String field: CloudAccount
	if !m.CloudAccount.IsNull() && !m.CloudAccount.IsUnknown() {
		proto.CloudAccount = m.CloudAccount.ValueString()
	}

	return proto
}

// ToCreateRequest converts a NetworkModel to a CreateNetworkRequest
func (m *NetworkModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateNetworkRequest {
	if m == nil {
		return nil
	}

	// Generate resource ID
	prefix := tfresource.GetResourcePrefix("Network")
	id, err := tfresource.GenerateResourceID(prefix)
	if err != nil {
		diags.AddError("ID Generation Error", fmt.Sprintf("Failed to generate resource ID: %s", err))
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}
	// Set the full resource name
	resource.Name = fmt.Sprintf("%s/networks/%s", parent, id)

	return &configpb.CreateNetworkRequest{
		Parent:    parent,
		Network:   resource,
		NetworkId: id,
	}
}

// ToUpdateRequest converts a NetworkModel to an UpdateNetworkRequest
func (m *NetworkModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateNetworkRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateNetworkRequest{
		Network: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a NetworkModel from a configpb.Network message
func (m *NetworkModel) FromProto(ctx context.Context, proto *configpb.Network, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/networks/network-abc"
	m.Fabric = extractParentNetworkString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// Map field: Tags
	if len(proto.Tags) > 0 {
		elements := make(map[string]types.String, len(proto.Tags))
		for k, v := range proto.Tags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Tags = mapValue
	} else if !m.Tags.IsNull() {
		m.Tags = types.MapNull(types.StringType)
	}
	// Map field: CloudResourceTags
	if len(proto.CloudResourceTags) > 0 {
		elements := make(map[string]types.String, len(proto.CloudResourceTags))
		for k, v := range proto.CloudResourceTags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.CloudResourceTags = mapValue
	} else if !m.CloudResourceTags.IsNull() {
		m.CloudResourceTags = types.MapNull(types.StringType)
	}
	// Enum field: PerformanceClass
	if proto.GetPerformanceClass() != 0 {
		m.PerformanceClass = types.StringValue(proto.GetPerformanceClass().String())
	} else if !m.PerformanceClass.IsNull() {
		m.PerformanceClass = types.StringNull()
	}
	// Object: Aws
	if proto.GetAws() != nil {
		var intermediate NetworkAWSDetails
		intermediate.FromProto(ctx, proto.GetAws(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, NetworkAWSDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Aws = objValue
	} else {
		m.Aws = types.ObjectNull(NetworkAWSDetailsAttrTypes())
	}
	// Object: Gcp
	if proto.GetGcp() != nil {
		var intermediate NetworkGCPDetails
		intermediate.FromProto(ctx, proto.GetGcp(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, NetworkGCPDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Gcp = objValue
	} else {
		m.Gcp = types.ObjectNull(NetworkGCPDetailsAttrTypes())
	}
	// Object: Azure
	if proto.GetAzure() != nil {
		var intermediate NetworkAzureDetails
		intermediate.FromProto(ctx, proto.GetAzure(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, NetworkAzureDetailsAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Azure = objValue
	} else {
		m.Azure = types.ObjectNull(NetworkAzureDetailsAttrTypes())
	}
	// String field: CloudAccount
	if proto.GetCloudAccount() != "" {
		m.CloudAccount = types.StringValue(proto.GetCloudAccount())
	} else if !m.CloudAccount.IsNull() {
		m.CloudAccount = types.StringValue("")
	}
}

// ToProto converts a NetworkAWSDetails to a configpb.Network_AWSDetails message
func (m *NetworkAWSDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_AWSDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_AWSDetails{}
	// String field: VpcId
	if !m.VpcId.IsNull() && !m.VpcId.IsUnknown() {
		proto.VpcId = m.VpcId.ValueString()
	}
	// List field: Subnets
	if !m.Subnets.IsNull() && !m.Subnets.IsUnknown() {
		var intermediates []NetworkAWSDetailsSubnet
		diags.Append(m.Subnets.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Subnets = append(proto.Subnets, item.ToProto(ctx, diags))
			}
		}
	}

	return proto
}

// FromProto populates a NetworkAWSDetails from a configpb.Network_AWSDetails message
func (m *NetworkAWSDetails) FromProto(ctx context.Context, proto *configpb.Network_AWSDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: VpcId
	if proto.GetVpcId() != "" {
		m.VpcId = types.StringValue(proto.GetVpcId())
	} else if !m.VpcId.IsNull() {
		m.VpcId = types.StringValue("")
	}
	// List field: Subnets
	if len(proto.Subnets) > 0 {
		// List of objects
		intermediates := make([]NetworkAWSDetailsSubnet, len(proto.Subnets))
		for i, item := range proto.Subnets {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: NetworkAWSDetailsSubnetAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Subnets = listValue
	} else {
		m.Subnets = types.ListNull(types.ObjectType{AttrTypes: NetworkAWSDetailsSubnetAttrTypes()})
	}
}

// ToProto converts a NetworkAWSDetailsSubnet to a configpb.Network_AWSDetails_Subnet message
func (m *NetworkAWSDetailsSubnet) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_AWSDetails_Subnet {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_AWSDetails_Subnet{}
	// String field: PublicSubnetId
	if !m.PublicSubnetId.IsNull() && !m.PublicSubnetId.IsUnknown() {
		proto.PublicSubnetId = m.PublicSubnetId.ValueString()
	}
	// String field: Eip
	if !m.Eip.IsNull() && !m.Eip.IsUnknown() {
		proto.Eip = m.Eip.ValueString()
	}

	return proto
}

// FromProto populates a NetworkAWSDetailsSubnet from a configpb.Network_AWSDetails_Subnet message
func (m *NetworkAWSDetailsSubnet) FromProto(ctx context.Context, proto *configpb.Network_AWSDetails_Subnet, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: PublicSubnetId
	if proto.GetPublicSubnetId() != "" {
		m.PublicSubnetId = types.StringValue(proto.GetPublicSubnetId())
	} else if !m.PublicSubnetId.IsNull() {
		m.PublicSubnetId = types.StringValue("")
	}
	// String field: Eip
	if proto.GetEip() != "" {
		m.Eip = types.StringValue(proto.GetEip())
	} else if !m.Eip.IsNull() {
		m.Eip = types.StringValue("")
	}
}

// ToProto converts a NetworkAzureDetails to a configpb.Network_AzureDetails message
func (m *NetworkAzureDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_AzureDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_AzureDetails{}
	// String field: VnetId
	if !m.VnetId.IsNull() && !m.VnetId.IsUnknown() {
		proto.VnetId = m.VnetId.ValueString()
	}
	// List field: Subnets
	if !m.Subnets.IsNull() && !m.Subnets.IsUnknown() {
		var intermediates []NetworkAzureDetailsSubnet
		diags.Append(m.Subnets.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Subnets = append(proto.Subnets, item.ToProto(ctx, diags))
			}
		}
	}

	return proto
}

// FromProto populates a NetworkAzureDetails from a configpb.Network_AzureDetails message
func (m *NetworkAzureDetails) FromProto(ctx context.Context, proto *configpb.Network_AzureDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: VnetId
	if proto.GetVnetId() != "" {
		m.VnetId = types.StringValue(proto.GetVnetId())
	} else if !m.VnetId.IsNull() {
		m.VnetId = types.StringValue("")
	}
	// List field: Subnets
	if len(proto.Subnets) > 0 {
		// List of objects
		intermediates := make([]NetworkAzureDetailsSubnet, len(proto.Subnets))
		for i, item := range proto.Subnets {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: NetworkAzureDetailsSubnetAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Subnets = listValue
	} else {
		m.Subnets = types.ListNull(types.ObjectType{AttrTypes: NetworkAzureDetailsSubnetAttrTypes()})
	}
}

// ToProto converts a NetworkAzureDetailsSubnet to a configpb.Network_AzureDetails_Subnet message
func (m *NetworkAzureDetailsSubnet) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_AzureDetails_Subnet {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_AzureDetails_Subnet{}
	// String field: PublicSubnetId
	if !m.PublicSubnetId.IsNull() && !m.PublicSubnetId.IsUnknown() {
		proto.PublicSubnetId = m.PublicSubnetId.ValueString()
	}
	// String field: AvailabilityZone
	if !m.AvailabilityZone.IsNull() && !m.AvailabilityZone.IsUnknown() {
		proto.AvailabilityZone = m.AvailabilityZone.ValueString()
	}

	return proto
}

// FromProto populates a NetworkAzureDetailsSubnet from a configpb.Network_AzureDetails_Subnet message
func (m *NetworkAzureDetailsSubnet) FromProto(ctx context.Context, proto *configpb.Network_AzureDetails_Subnet, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: PublicSubnetId
	if proto.GetPublicSubnetId() != "" {
		m.PublicSubnetId = types.StringValue(proto.GetPublicSubnetId())
	} else if !m.PublicSubnetId.IsNull() {
		m.PublicSubnetId = types.StringValue("")
	}
	// String field: AvailabilityZone
	if proto.GetAvailabilityZone() != "" {
		m.AvailabilityZone = types.StringValue(proto.GetAvailabilityZone())
	} else if !m.AvailabilityZone.IsNull() {
		m.AvailabilityZone = types.StringValue("")
	}
}

// ToProto converts a NetworkGCPDetails to a configpb.Network_GCPDetails message
func (m *NetworkGCPDetails) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_GCPDetails {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_GCPDetails{}
	// String field: VpcId
	if !m.VpcId.IsNull() && !m.VpcId.IsUnknown() {
		proto.VpcId = m.VpcId.ValueString()
	}
	// List field: Subnets
	if !m.Subnets.IsNull() && !m.Subnets.IsUnknown() {
		var intermediates []NetworkGCPDetailsSubnet
		diags.Append(m.Subnets.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Subnets = append(proto.Subnets, item.ToProto(ctx, diags))
			}
		}
	}

	return proto
}

// FromProto populates a NetworkGCPDetails from a configpb.Network_GCPDetails message
func (m *NetworkGCPDetails) FromProto(ctx context.Context, proto *configpb.Network_GCPDetails, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: VpcId
	if proto.GetVpcId() != "" {
		m.VpcId = types.StringValue(proto.GetVpcId())
	} else if !m.VpcId.IsNull() {
		m.VpcId = types.StringValue("")
	}
	// List field: Subnets
	if len(proto.Subnets) > 0 {
		// List of objects
		intermediates := make([]NetworkGCPDetailsSubnet, len(proto.Subnets))
		for i, item := range proto.Subnets {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: NetworkGCPDetailsSubnetAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Subnets = listValue
	} else {
		m.Subnets = types.ListNull(types.ObjectType{AttrTypes: NetworkGCPDetailsSubnetAttrTypes()})
	}
}

// ToProto converts a NetworkGCPDetailsSubnet to a configpb.Network_GCPDetails_Subnet message
func (m *NetworkGCPDetailsSubnet) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.Network_GCPDetails_Subnet {
	if m == nil {
		return nil
	}

	proto := &configpb.Network_GCPDetails_Subnet{}
	// String field: PublicSubnetId
	if !m.PublicSubnetId.IsNull() && !m.PublicSubnetId.IsUnknown() {
		proto.PublicSubnetId = m.PublicSubnetId.ValueString()
	}
	// String field: AvailabilityZone
	if !m.AvailabilityZone.IsNull() && !m.AvailabilityZone.IsUnknown() {
		proto.AvailabilityZone = m.AvailabilityZone.ValueString()
	}

	return proto
}

// FromProto populates a NetworkGCPDetailsSubnet from a configpb.Network_GCPDetails_Subnet message
func (m *NetworkGCPDetailsSubnet) FromProto(ctx context.Context, proto *configpb.Network_GCPDetails_Subnet, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: PublicSubnetId
	if proto.GetPublicSubnetId() != "" {
		m.PublicSubnetId = types.StringValue(proto.GetPublicSubnetId())
	} else if !m.PublicSubnetId.IsNull() {
		m.PublicSubnetId = types.StringValue("")
	}
	// String field: AvailabilityZone
	if proto.GetAvailabilityZone() != "" {
		m.AvailabilityZone = types.StringValue(proto.GetAvailabilityZone())
	} else if !m.AvailabilityZone.IsNull() {
		m.AvailabilityZone = types.StringValue("")
	}
}

// NetworkAWSDetailsAttrTypes returns the attribute types for NetworkAWSDetails
func NetworkAWSDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"vpc_id":  types.StringType,
		"subnets": types.ListType{ElemType: types.ObjectType{AttrTypes: NetworkAWSDetailsSubnetAttrTypes()}},
	}
}

// NetworkAWSDetailsSubnetAttrTypes returns the attribute types for NetworkAWSDetailsSubnet
func NetworkAWSDetailsSubnetAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"public_subnet_id": types.StringType,
		"eip":              types.StringType,
	}
}

// NetworkAzureDetailsAttrTypes returns the attribute types for NetworkAzureDetails
func NetworkAzureDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"vnet_id": types.StringType,
		"subnets": types.ListType{ElemType: types.ObjectType{AttrTypes: NetworkAzureDetailsSubnetAttrTypes()}},
	}
}

// NetworkAzureDetailsSubnetAttrTypes returns the attribute types for NetworkAzureDetailsSubnet
func NetworkAzureDetailsSubnetAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"public_subnet_id":  types.StringType,
		"availability_zone": types.StringType,
	}
}

// NetworkGCPDetailsAttrTypes returns the attribute types for NetworkGCPDetails
func NetworkGCPDetailsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"vpc_id":  types.StringType,
		"subnets": types.ListType{ElemType: types.ObjectType{AttrTypes: NetworkGCPDetailsSubnetAttrTypes()}},
	}
}

// NetworkGCPDetailsSubnetAttrTypes returns the attribute types for NetworkGCPDetailsSubnet
func NetworkGCPDetailsSubnetAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"public_subnet_id":  types.StringType,
		"availability_zone": types.StringType,
	}
}

// extractParentNetworkString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/networks/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentNetworkString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/networks/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
