// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/network_inspection.proto
// generatedFile: aviatrix/config/v1alpha/network_inspection_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NetworkInspectionModel struct {
	Fabric      types.String `tfsdk:"fabric"`
	Name        types.String `tfsdk:"name"`
	Network     types.String `tfsdk:"network"`
	Egress      types.Object `tfsdk:"egress"`
	AwsEastWest types.Object `tfsdk:"aws_east_west"`
}

type NetworkInspectionAwsEastWest struct {
	Scope         types.String `tfsdk:"scope"`
	RouteTableIds types.List   `tfsdk:"route_table_ids"`
}

type NetworkInspectionEgress struct {
	Enabled              types.Bool `tfsdk:"enabled"`
	PrivateRouteTableIds types.List `tfsdk:"private_route_table_ids"`
}

func NetworkInspectionAwsEastWestAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf(
					"SCOPE_SELECTED",
				),
			},
		},
		"route_table_ids": schema.ListAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}
func NetworkInspectionEgressAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"enabled": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"private_route_table_ids": schema.ListAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}

func NetworkInspectionSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"network": schema.StringAttribute{
				Description: "",
				Required:    true,
			},
			"egress": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  NetworkInspectionEgressAttributes(),
			},
			"aws_east_west": schema.SingleNestedAttribute{
				Description: "",
				Optional:    true,
				Attributes:  NetworkInspectionAwsEastWestAttributes(),
			},
		},
	}
}
