// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/smart_group.proto
// generatedFile: aviatrix/config/v1alpha/smart_group_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SmartGroupModel struct {
	Fabric         types.String `tfsdk:"fabric"`
	Name           types.String `tfsdk:"name"`
	DisplayName    types.String `tfsdk:"display_name"`
	Selector       types.Object `tfsdk:"selector"`
	SystemResource types.Bool   `tfsdk:"system_resource"`
}

type SmartGroupKubernetesPodMatch struct {
	ClusterId types.String `tfsdk:"cluster_id"`
	Namespace types.String `tfsdk:"namespace"`
	Service   types.String `tfsdk:"service"`
	Labels    types.Map    `tfsdk:"labels"`
}

type SmartGroupMatch struct {
	Cidr   types.String `tfsdk:"cidr"`
	Fqdn   types.String `tfsdk:"fqdn"`
	Vm     types.Object `tfsdk:"vm"`
	Vpc    types.Object `tfsdk:"vpc"`
	Subnet types.Object `tfsdk:"subnet"`
	Pod    types.Object `tfsdk:"pod"`
}

type SmartGroupSelector struct {
	Match types.List `tfsdk:"match"`
}

type SmartGroupSubnetMatch struct {
	Name         types.String `tfsdk:"name"`
	CloudAccount types.String `tfsdk:"cloud_account"`
	Region       types.String `tfsdk:"region"`
	Tags         types.Map    `tfsdk:"tags"`
}

type SmartGroupVMMatch struct {
	Name         types.String `tfsdk:"name"`
	CloudAccount types.String `tfsdk:"cloud_account"`
	Region       types.String `tfsdk:"region"`
	Tags         types.Map    `tfsdk:"tags"`
}

type SmartGroupVPCMatch struct {
	Name         types.String `tfsdk:"name"`
	CloudAccount types.String `tfsdk:"cloud_account"`
	Region       types.String `tfsdk:"region"`
	Tags         types.Map    `tfsdk:"tags"`
}

func SmartGroupKubernetesPodMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"cluster_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"namespace": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"service": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"labels": schema.MapAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}
func SmartGroupMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"cidr": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"fqdn": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"vm": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  SmartGroupVMMatchAttributes(),
		},
		"vpc": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  SmartGroupVPCMatchAttributes(),
		},
		"subnet": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  SmartGroupSubnetMatchAttributes(),
		},
		"pod": schema.SingleNestedAttribute{
			Description: "",
			Optional:    true,
			Attributes:  SmartGroupKubernetesPodMatchAttributes(),
		},
	}
}
func SmartGroupSelectorAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"match": schema.ListNestedAttribute{
			Description: "",
			Required:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: SmartGroupMatchAttributes(),
			},
		},
	}
}
func SmartGroupSubnetMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cloud_account": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"region": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tags": schema.MapAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}
func SmartGroupVMMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cloud_account": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"region": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tags": schema.MapAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}
func SmartGroupVPCMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cloud_account": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"region": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tags": schema.MapAttribute{
			Description: "",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}

func SmartGroupSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Required:    true,
			},
			"selector": schema.SingleNestedAttribute{
				Description: "",
				Required:    true,
				Attributes:  SmartGroupSelectorAttributes(),
			},
			"system_resource": schema.BoolAttribute{
				Description: "",
				Computed:    true,
			},
		},
	}
}
