// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/smart_group.proto
// generatedFile: aviatrix/config/v1alpha/smart_group_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a SmartGroupModel to a configpb.SmartGroup message
func (m *SmartGroupModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// Object: Selector
	if !m.Selector.IsNull() && !m.Selector.IsUnknown() {
		var intermediate SmartGroupSelector
		diags.Append(m.Selector.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Selector = intermediate.ToProto(ctx, diags)
		}
	}

	return proto
}

// ToCreateRequest converts a SmartGroupModel to a CreateSmartGroupRequest
func (m *SmartGroupModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateSmartGroupRequest {
	if m == nil {
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.CreateSmartGroupRequest{
		Parent:     parent,
		SmartGroup: resource,
	}
}

// ToUpdateRequest converts a SmartGroupModel to an UpdateSmartGroupRequest
func (m *SmartGroupModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateSmartGroupRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateSmartGroupRequest{
		SmartGroup: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a SmartGroupModel from a configpb.SmartGroup message
func (m *SmartGroupModel) FromProto(ctx context.Context, proto *configpb.SmartGroup, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/smartGroups/smartGroup-abc"
	m.Fabric = extractParentSmartGroupString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// Object: Selector
	if proto.GetSelector() != nil {
		var intermediate SmartGroupSelector
		intermediate.FromProto(ctx, proto.GetSelector(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, SmartGroupSelectorAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Selector = objValue
	} else {
		m.Selector = types.ObjectNull(SmartGroupSelectorAttrTypes())
	}
	// Bool field: SystemResource
	if proto.GetSystemResource() != false {
		m.SystemResource = types.BoolValue(proto.GetSystemResource())
	} else {
		m.SystemResource = types.BoolValue(false)
	}
}

// ToProto converts a SmartGroupKubernetesPodMatch to a configpb.SmartGroup_KubernetesPodMatch message
func (m *SmartGroupKubernetesPodMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_KubernetesPodMatch {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_KubernetesPodMatch{}
	// String field: ClusterId
	if !m.ClusterId.IsNull() && !m.ClusterId.IsUnknown() {
		proto.ClusterId = m.ClusterId.ValueString()
	}
	// String field: Namespace
	if !m.Namespace.IsNull() && !m.Namespace.IsUnknown() {
		proto.Namespace = m.Namespace.ValueString()
	}
	// String field: Service
	if !m.Service.IsNull() && !m.Service.IsUnknown() {
		proto.Service = m.Service.ValueString()
	}
	// Map field: Labels
	if !m.Labels.IsNull() && !m.Labels.IsUnknown() {
		elements := make(map[string]types.String, len(m.Labels.Elements()))
		diags.Append(m.Labels.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Labels = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Labels[k] = v.ValueString()
				}
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupKubernetesPodMatch from a configpb.SmartGroup_KubernetesPodMatch message
func (m *SmartGroupKubernetesPodMatch) FromProto(ctx context.Context, proto *configpb.SmartGroup_KubernetesPodMatch, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: ClusterId
	if proto.GetClusterId() != "" {
		m.ClusterId = types.StringValue(proto.GetClusterId())
	} else if !m.ClusterId.IsNull() {
		m.ClusterId = types.StringValue("")
	}
	// String field: Namespace
	if proto.GetNamespace() != "" {
		m.Namespace = types.StringValue(proto.GetNamespace())
	} else if !m.Namespace.IsNull() {
		m.Namespace = types.StringValue("")
	}
	// String field: Service
	if proto.GetService() != "" {
		m.Service = types.StringValue(proto.GetService())
	} else if !m.Service.IsNull() {
		m.Service = types.StringValue("")
	}
	// Map field: Labels
	if len(proto.Labels) > 0 {
		elements := make(map[string]types.String, len(proto.Labels))
		for k, v := range proto.Labels {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Labels = mapValue
	} else if !m.Labels.IsNull() {
		m.Labels = types.MapNull(types.StringType)
	}
}

// ToProto converts a SmartGroupMatch to a configpb.SmartGroup_Match message
func (m *SmartGroupMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_Match {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_Match{}
	// Oneof string field: Cidr
	if !m.Cidr.IsNull() && !m.Cidr.IsUnknown() {
		proto.MatchType = &configpb.SmartGroup_Match_Cidr{
			Cidr: m.Cidr.ValueString(),
		}
	}
	// Oneof string field: Fqdn
	if !m.Fqdn.IsNull() && !m.Fqdn.IsUnknown() {
		proto.MatchType = &configpb.SmartGroup_Match_Fqdn{
			Fqdn: m.Fqdn.ValueString(),
		}
	}
	// Oneof object field: Vm
	if !m.Vm.IsNull() && !m.Vm.IsUnknown() {
		var intermediate SmartGroupVMMatch
		diags.Append(m.Vm.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.MatchType = &configpb.SmartGroup_Match_Vm{
				Vm: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Vpc
	if !m.Vpc.IsNull() && !m.Vpc.IsUnknown() {
		var intermediate SmartGroupVPCMatch
		diags.Append(m.Vpc.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.MatchType = &configpb.SmartGroup_Match_Vpc{
				Vpc: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Subnet
	if !m.Subnet.IsNull() && !m.Subnet.IsUnknown() {
		var intermediate SmartGroupSubnetMatch
		diags.Append(m.Subnet.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.MatchType = &configpb.SmartGroup_Match_Subnet{
				Subnet: intermediate.ToProto(ctx, diags),
			}
		}
	}
	// Oneof object field: Pod
	if !m.Pod.IsNull() && !m.Pod.IsUnknown() {
		var intermediate SmartGroupKubernetesPodMatch
		diags.Append(m.Pod.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.MatchType = &configpb.SmartGroup_Match_Pod{
				Pod: intermediate.ToProto(ctx, diags),
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupMatch from a configpb.SmartGroup_Match message
func (m *SmartGroupMatch) FromProto(ctx context.Context, proto *configpb.SmartGroup_Match, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: Cidr
	if proto.GetCidr() != "" {
		m.Cidr = types.StringValue(proto.GetCidr())
	} else if !m.Cidr.IsNull() {
		m.Cidr = types.StringValue("")
	}
	// String field: Fqdn
	if proto.GetFqdn() != "" {
		m.Fqdn = types.StringValue(proto.GetFqdn())
	} else if !m.Fqdn.IsNull() {
		m.Fqdn = types.StringValue("")
	}
	// Object: Vm
	if proto.GetVm() != nil {
		var intermediate SmartGroupVMMatch
		intermediate.FromProto(ctx, proto.GetVm(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, SmartGroupVMMatchAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Vm = objValue
	} else {
		m.Vm = types.ObjectNull(SmartGroupVMMatchAttrTypes())
	}
	// Object: Vpc
	if proto.GetVpc() != nil {
		var intermediate SmartGroupVPCMatch
		intermediate.FromProto(ctx, proto.GetVpc(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, SmartGroupVPCMatchAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Vpc = objValue
	} else {
		m.Vpc = types.ObjectNull(SmartGroupVPCMatchAttrTypes())
	}
	// Object: Subnet
	if proto.GetSubnet() != nil {
		var intermediate SmartGroupSubnetMatch
		intermediate.FromProto(ctx, proto.GetSubnet(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, SmartGroupSubnetMatchAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Subnet = objValue
	} else {
		m.Subnet = types.ObjectNull(SmartGroupSubnetMatchAttrTypes())
	}
	// Object: Pod
	if proto.GetPod() != nil {
		var intermediate SmartGroupKubernetesPodMatch
		intermediate.FromProto(ctx, proto.GetPod(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, SmartGroupKubernetesPodMatchAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Pod = objValue
	} else {
		m.Pod = types.ObjectNull(SmartGroupKubernetesPodMatchAttrTypes())
	}
}

// ToProto converts a SmartGroupSelector to a configpb.SmartGroup_Selector message
func (m *SmartGroupSelector) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_Selector {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_Selector{}
	// List field: Match
	if !m.Match.IsNull() && !m.Match.IsUnknown() {
		var intermediates []SmartGroupMatch
		diags.Append(m.Match.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Match = append(proto.Match, item.ToProto(ctx, diags))
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupSelector from a configpb.SmartGroup_Selector message
func (m *SmartGroupSelector) FromProto(ctx context.Context, proto *configpb.SmartGroup_Selector, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// List field: Match
	if len(proto.Match) > 0 {
		// List of objects
		intermediates := make([]SmartGroupMatch, len(proto.Match))
		for i, item := range proto.Match {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: SmartGroupMatchAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Match = listValue
	} else {
		m.Match = types.ListNull(types.ObjectType{AttrTypes: SmartGroupMatchAttrTypes()})
	}
}

// ToProto converts a SmartGroupSubnetMatch to a configpb.SmartGroup_SubnetMatch message
func (m *SmartGroupSubnetMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_SubnetMatch {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_SubnetMatch{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: CloudAccount
	if !m.CloudAccount.IsNull() && !m.CloudAccount.IsUnknown() {
		proto.CloudAccount = m.CloudAccount.ValueString()
	}
	// String field: Region
	if !m.Region.IsNull() && !m.Region.IsUnknown() {
		proto.Region = m.Region.ValueString()
	}
	// Map field: Tags
	if !m.Tags.IsNull() && !m.Tags.IsUnknown() {
		elements := make(map[string]types.String, len(m.Tags.Elements()))
		diags.Append(m.Tags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Tags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Tags[k] = v.ValueString()
				}
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupSubnetMatch from a configpb.SmartGroup_SubnetMatch message
func (m *SmartGroupSubnetMatch) FromProto(ctx context.Context, proto *configpb.SmartGroup_SubnetMatch, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else if !m.Name.IsNull() {
		m.Name = types.StringValue("")
	}
	// String field: CloudAccount
	if proto.GetCloudAccount() != "" {
		m.CloudAccount = types.StringValue(proto.GetCloudAccount())
	} else if !m.CloudAccount.IsNull() {
		m.CloudAccount = types.StringValue("")
	}
	// String field: Region
	if proto.GetRegion() != "" {
		m.Region = types.StringValue(proto.GetRegion())
	} else if !m.Region.IsNull() {
		m.Region = types.StringValue("")
	}
	// Map field: Tags
	if len(proto.Tags) > 0 {
		elements := make(map[string]types.String, len(proto.Tags))
		for k, v := range proto.Tags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Tags = mapValue
	} else if !m.Tags.IsNull() {
		m.Tags = types.MapNull(types.StringType)
	}
}

// ToProto converts a SmartGroupVMMatch to a configpb.SmartGroup_VMMatch message
func (m *SmartGroupVMMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_VMMatch {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_VMMatch{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: CloudAccount
	if !m.CloudAccount.IsNull() && !m.CloudAccount.IsUnknown() {
		proto.CloudAccount = m.CloudAccount.ValueString()
	}
	// String field: Region
	if !m.Region.IsNull() && !m.Region.IsUnknown() {
		proto.Region = m.Region.ValueString()
	}
	// Map field: Tags
	if !m.Tags.IsNull() && !m.Tags.IsUnknown() {
		elements := make(map[string]types.String, len(m.Tags.Elements()))
		diags.Append(m.Tags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Tags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Tags[k] = v.ValueString()
				}
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupVMMatch from a configpb.SmartGroup_VMMatch message
func (m *SmartGroupVMMatch) FromProto(ctx context.Context, proto *configpb.SmartGroup_VMMatch, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else if !m.Name.IsNull() {
		m.Name = types.StringValue("")
	}
	// String field: CloudAccount
	if proto.GetCloudAccount() != "" {
		m.CloudAccount = types.StringValue(proto.GetCloudAccount())
	} else if !m.CloudAccount.IsNull() {
		m.CloudAccount = types.StringValue("")
	}
	// String field: Region
	if proto.GetRegion() != "" {
		m.Region = types.StringValue(proto.GetRegion())
	} else if !m.Region.IsNull() {
		m.Region = types.StringValue("")
	}
	// Map field: Tags
	if len(proto.Tags) > 0 {
		elements := make(map[string]types.String, len(proto.Tags))
		for k, v := range proto.Tags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Tags = mapValue
	} else if !m.Tags.IsNull() {
		m.Tags = types.MapNull(types.StringType)
	}
}

// ToProto converts a SmartGroupVPCMatch to a configpb.SmartGroup_VPCMatch message
func (m *SmartGroupVPCMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.SmartGroup_VPCMatch {
	if m == nil {
		return nil
	}

	proto := &configpb.SmartGroup_VPCMatch{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: CloudAccount
	if !m.CloudAccount.IsNull() && !m.CloudAccount.IsUnknown() {
		proto.CloudAccount = m.CloudAccount.ValueString()
	}
	// String field: Region
	if !m.Region.IsNull() && !m.Region.IsUnknown() {
		proto.Region = m.Region.ValueString()
	}
	// Map field: Tags
	if !m.Tags.IsNull() && !m.Tags.IsUnknown() {
		elements := make(map[string]types.String, len(m.Tags.Elements()))
		diags.Append(m.Tags.ElementsAs(ctx, &elements, false)...)
		if !diags.HasError() {
			proto.Tags = make(map[string]string, len(elements))
			for k, v := range elements {
				if !v.IsNull() && !v.IsUnknown() {
					proto.Tags[k] = v.ValueString()
				}
			}
		}
	}

	return proto
}

// FromProto populates a SmartGroupVPCMatch from a configpb.SmartGroup_VPCMatch message
func (m *SmartGroupVPCMatch) FromProto(ctx context.Context, proto *configpb.SmartGroup_VPCMatch, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else if !m.Name.IsNull() {
		m.Name = types.StringValue("")
	}
	// String field: CloudAccount
	if proto.GetCloudAccount() != "" {
		m.CloudAccount = types.StringValue(proto.GetCloudAccount())
	} else if !m.CloudAccount.IsNull() {
		m.CloudAccount = types.StringValue("")
	}
	// String field: Region
	if proto.GetRegion() != "" {
		m.Region = types.StringValue(proto.GetRegion())
	} else if !m.Region.IsNull() {
		m.Region = types.StringValue("")
	}
	// Map field: Tags
	if len(proto.Tags) > 0 {
		elements := make(map[string]types.String, len(proto.Tags))
		for k, v := range proto.Tags {
			elements[k] = types.StringValue(v)
		}
		mapValue, mapDiags := types.MapValueFrom(ctx, types.StringType, elements)
		diags.Append(mapDiags...)
		m.Tags = mapValue
	} else if !m.Tags.IsNull() {
		m.Tags = types.MapNull(types.StringType)
	}
}

// SmartGroupKubernetesPodMatchAttrTypes returns the attribute types for SmartGroupKubernetesPodMatch
func SmartGroupKubernetesPodMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"cluster_id": types.StringType,
		"namespace":  types.StringType,
		"service":    types.StringType,
		"labels":     types.MapType{ElemType: types.StringType},
	}
}

// SmartGroupMatchAttrTypes returns the attribute types for SmartGroupMatch
func SmartGroupMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"cidr":   types.StringType,
		"fqdn":   types.StringType,
		"vm":     types.ObjectType{AttrTypes: SmartGroupVMMatchAttrTypes()},
		"vpc":    types.ObjectType{AttrTypes: SmartGroupVPCMatchAttrTypes()},
		"subnet": types.ObjectType{AttrTypes: SmartGroupSubnetMatchAttrTypes()},
		"pod":    types.ObjectType{AttrTypes: SmartGroupKubernetesPodMatchAttrTypes()},
	}
}

// SmartGroupSelectorAttrTypes returns the attribute types for SmartGroupSelector
func SmartGroupSelectorAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"match": types.ListType{ElemType: types.ObjectType{AttrTypes: SmartGroupMatchAttrTypes()}},
	}
}

// SmartGroupSubnetMatchAttrTypes returns the attribute types for SmartGroupSubnetMatch
func SmartGroupSubnetMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":          types.StringType,
		"cloud_account": types.StringType,
		"region":        types.StringType,
		"tags":          types.MapType{ElemType: types.StringType},
	}
}

// SmartGroupVMMatchAttrTypes returns the attribute types for SmartGroupVMMatch
func SmartGroupVMMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":          types.StringType,
		"cloud_account": types.StringType,
		"region":        types.StringType,
		"tags":          types.MapType{ElemType: types.StringType},
	}
}

// SmartGroupVPCMatchAttrTypes returns the attribute types for SmartGroupVPCMatch
func SmartGroupVPCMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":          types.StringType,
		"cloud_account": types.StringType,
		"region":        types.StringType,
		"tags":          types.MapType{ElemType: types.StringType},
	}
}

// extractParentSmartGroupString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/smartGroups/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentSmartGroupString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/smartGroups/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
