// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/web_group.proto
// generatedFile: aviatrix/config/v1alpha/web_group_converter_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"context"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/genproto/protobuf/field_mask"
	configpb "github.com/AviatrixSystems/terraform-provider-avxcloud/internal/gen-protogo/aviatrix/config/v1alpha"
)

// ToProto converts a WebGroupModel to a configpb.WebGroup message
func (m *WebGroupModel) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.WebGroup {
	if m == nil {
		return nil
	}

	proto := &configpb.WebGroup{}
	// String field: Name
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		proto.Name = m.Name.ValueString()
	}
	// String field: DisplayName
	if !m.DisplayName.IsNull() && !m.DisplayName.IsUnknown() {
		proto.DisplayName = m.DisplayName.ValueString()
	}
	// Object: Selector
	if !m.Selector.IsNull() && !m.Selector.IsUnknown() {
		var intermediate WebGroupSelector
		diags.Append(m.Selector.As(ctx, &intermediate, basetypes.ObjectAsOptions{})...)
		if !diags.HasError() {
			proto.Selector = intermediate.ToProto(ctx, diags)
		}
	}

	return proto
}

// ToCreateRequest converts a WebGroupModel to a CreateWebGroupRequest
func (m *WebGroupModel) ToCreateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.CreateWebGroupRequest {
	if m == nil {
		return nil
	}
	// Construct parent path from fabric
	parent := m.Fabric.ValueString()

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.CreateWebGroupRequest{
		Parent:   parent,
		WebGroup: resource,
	}
}

// ToUpdateRequest converts a WebGroupModel to an UpdateWebGroupRequest
func (m *WebGroupModel) ToUpdateRequest(ctx context.Context, diags *diag.Diagnostics) *configpb.UpdateWebGroupRequest {
	if m == nil {
		return nil
	}

	resource := m.ToProto(ctx, diags)
	if diags.HasError() {
		return nil
	}

	return &configpb.UpdateWebGroupRequest{
		WebGroup: resource,
		UpdateMask: &field_mask.FieldMask{
			Paths: []string{"*"},
		},
	}
}

// FromProto populates a WebGroupModel from a configpb.WebGroup message
func (m *WebGroupModel) FromProto(ctx context.Context, proto *configpb.WebGroup, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// Extract parent fabric from resource name
	// Format: "fabrics/fab-xyz/webGroups/webGroup-abc"
	m.Fabric = extractParentWebGroupString(proto.Name)
	// String field: Name
	if proto.GetName() != "" {
		m.Name = types.StringValue(proto.GetName())
	} else {
		m.Name = types.StringValue("")
	}
	// String field: DisplayName
	if proto.GetDisplayName() != "" {
		m.DisplayName = types.StringValue(proto.GetDisplayName())
	} else if !m.DisplayName.IsNull() {
		m.DisplayName = types.StringValue("")
	}
	// Object: Selector
	if proto.GetSelector() != nil {
		var intermediate WebGroupSelector
		intermediate.FromProto(ctx, proto.GetSelector(), diags)

		objValue, objDiags := types.ObjectValueFrom(ctx, WebGroupSelectorAttrTypes(), intermediate)
		diags.Append(objDiags...)
		m.Selector = objValue
	} else {
		m.Selector = types.ObjectNull(WebGroupSelectorAttrTypes())
	}
	// Bool field: SystemResource
	if proto.GetSystemResource() != false {
		m.SystemResource = types.BoolValue(proto.GetSystemResource())
	} else {
		m.SystemResource = types.BoolValue(false)
	}
}

// ToProto converts a WebGroupMatch to a configpb.WebGroup_Match message
func (m *WebGroupMatch) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.WebGroup_Match {
	if m == nil {
		return nil
	}

	proto := &configpb.WebGroup_Match{}
	// Oneof string field: Url
	if !m.Url.IsNull() && !m.Url.IsUnknown() {
		proto.MatchType = &configpb.WebGroup_Match_Url{
			Url: m.Url.ValueString(),
		}
	}
	// Oneof string field: Sni
	if !m.Sni.IsNull() && !m.Sni.IsUnknown() {
		proto.MatchType = &configpb.WebGroup_Match_Sni{
			Sni: m.Sni.ValueString(),
		}
	}

	return proto
}

// FromProto populates a WebGroupMatch from a configpb.WebGroup_Match message
func (m *WebGroupMatch) FromProto(ctx context.Context, proto *configpb.WebGroup_Match, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// String field: Url
	if proto.GetUrl() != "" {
		m.Url = types.StringValue(proto.GetUrl())
	} else if !m.Url.IsNull() {
		m.Url = types.StringValue("")
	}
	// String field: Sni
	if proto.GetSni() != "" {
		m.Sni = types.StringValue(proto.GetSni())
	} else if !m.Sni.IsNull() {
		m.Sni = types.StringValue("")
	}
}

// ToProto converts a WebGroupSelector to a configpb.WebGroup_Selector message
func (m *WebGroupSelector) ToProto(ctx context.Context, diags *diag.Diagnostics) *configpb.WebGroup_Selector {
	if m == nil {
		return nil
	}

	proto := &configpb.WebGroup_Selector{}
	// List field: Match
	if !m.Match.IsNull() && !m.Match.IsUnknown() {
		var intermediates []WebGroupMatch
		diags.Append(m.Match.ElementsAs(ctx, &intermediates, false)...)
		if !diags.HasError() {
			for _, item := range intermediates {
				proto.Match = append(proto.Match, item.ToProto(ctx, diags))
			}
		}
	}

	return proto
}

// FromProto populates a WebGroupSelector from a configpb.WebGroup_Selector message
func (m *WebGroupSelector) FromProto(ctx context.Context, proto *configpb.WebGroup_Selector, diags *diag.Diagnostics) {
	if proto == nil {
		return
	}
	// List field: Match
	if len(proto.Match) > 0 {
		// List of objects
		intermediates := make([]WebGroupMatch, len(proto.Match))
		for i, item := range proto.Match {
			intermediates[i].FromProto(ctx, item, diags)
		}
		listValue, listDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: WebGroupMatchAttrTypes()}, intermediates)
		diags.Append(listDiags...)
		m.Match = listValue
	} else {
		m.Match = types.ListNull(types.ObjectType{AttrTypes: WebGroupMatchAttrTypes()})
	}
}

// WebGroupMatchAttrTypes returns the attribute types for WebGroupMatch
func WebGroupMatchAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"url": types.StringType,
		"sni": types.StringType,
	}
}

// WebGroupSelectorAttrTypes returns the attribute types for WebGroupSelector
func WebGroupSelectorAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"match": types.ListType{ElemType: types.ObjectType{AttrTypes: WebGroupMatchAttrTypes()}},
	}
}

// extractParentWebGroupString extracts the parent path from a resource name and returns types.String
// Example: "fabrics/fab-xyz/webGroups/net-abc" -> types.StringValue("fabrics/fab-xyz")
// If resourceName is empty or separator not found -> types.StringNull()
func extractParentWebGroupString(resourceName string) types.String {
	if resourceName == "" {
		return types.StringNull()
	}

	separator := "/webGroups/"
	idx := strings.LastIndex(resourceName, separator)
	if idx <= 0 {
		return types.StringNull()
	}

	return types.StringValue(resourceName[:idx])
}
