// Code generated by tools/terraform. DO NOT EDIT.
// source: aviatrix/config/v1alpha/web_group.proto
// generatedFile: aviatrix/config/v1alpha/web_group_schema_gen.go
//
// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

package terraform

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type WebGroupModel struct {
	Fabric         types.String `tfsdk:"fabric"`
	Name           types.String `tfsdk:"name"`
	DisplayName    types.String `tfsdk:"display_name"`
	Selector       types.Object `tfsdk:"selector"`
	SystemResource types.Bool   `tfsdk:"system_resource"`
}

type WebGroupMatch struct {
	Url types.String `tfsdk:"url"`
	Sni types.String `tfsdk:"sni"`
}

type WebGroupSelector struct {
	Match types.List `tfsdk:"match"`
}

func WebGroupMatchAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"sni": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}
}
func WebGroupSelectorAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"match": schema.ListNestedAttribute{
			Description: "",
			Required:    true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: WebGroupMatchAttributes(),
			},
		},
	}
}

func WebGroupSchema() schema.Schema {
	return schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"fabric": schema.StringAttribute{
				Description: "Parent fabric resource name",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Description: "",
				Required:    true,
			},
			"selector": schema.SingleNestedAttribute{
				Description: "",
				Required:    true,
				Attributes:  WebGroupSelectorAttributes(),
			},
			"system_resource": schema.BoolAttribute{
				Description: "",
				Computed:    true,
			},
		},
	}
}
