// Copyright Aviatrix Systems, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: aviatrix/api/annotations.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope of a resource within the API.
type ResourceDescriptor_Scope int32

const (
	// Indicates that scope was not set. This is typically an error.
	ResourceDescriptor_SCOPE_UNSPECIFIED ResourceDescriptor_Scope = 0
	// Indicates that a resource has no parent and do not appear under any sub-collections.
	ResourceDescriptor_SCOPE_GLOBAL ResourceDescriptor_Scope = 1
	// Indicates that a resource is a child of a particular fabric.
	ResourceDescriptor_SCOPE_FABRIC ResourceDescriptor_Scope = 2
	// Indicates that a resource is a child of a particular service account.
	ResourceDescriptor_SCOPE_SERVICE_ACCOUNT ResourceDescriptor_Scope = 3
)

// Enum value maps for ResourceDescriptor_Scope.
var (
	ResourceDescriptor_Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_GLOBAL",
		2: "SCOPE_FABRIC",
		3: "SCOPE_SERVICE_ACCOUNT",
	}
	ResourceDescriptor_Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED":     0,
		"SCOPE_GLOBAL":          1,
		"SCOPE_FABRIC":          2,
		"SCOPE_SERVICE_ACCOUNT": 3,
	}
)

func (x ResourceDescriptor_Scope) Enum() *ResourceDescriptor_Scope {
	p := new(ResourceDescriptor_Scope)
	*p = x
	return p
}

func (x ResourceDescriptor_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceDescriptor_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_aviatrix_api_annotations_proto_enumTypes[0].Descriptor()
}

func (ResourceDescriptor_Scope) Type() protoreflect.EnumType {
	return &file_aviatrix_api_annotations_proto_enumTypes[0]
}

func (x ResourceDescriptor_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceDescriptor_Scope.Descriptor instead.
func (ResourceDescriptor_Scope) EnumDescriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 0}
}

// ResourceDescriptor annotates a resource proto, indicating how a service based around
// the resource should be generated. The resource must additionally
// be annotated with google.api.resource.
type ResourceDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// external denotes if the message is exposed to the end user.
	// TODO: consider replacing with https://github.com/googleapis/googleapis/blob/master/google/api/visibility.proto.
	External bool `protobuf:"varint,1,opt,name=external,proto3" json:"external,omitempty"`
	// The scope of this resource within the API.
	Scope ResourceDescriptor_Scope `protobuf:"varint,2,opt,name=scope,proto3,enum=aviatrix.api.ResourceDescriptor_Scope" json:"scope,omitempty"`
	// Restrictions on identifiers for this resource.
	Id *ResourceDescriptor_IdentifierRestrictions `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Restrictions on listing resources of this type.
	List *ResourceDescriptor_ListRestrictions `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
	// Restrictions on the generated create method.
	Create *ResourceDescriptor_CreateRestrictions `protobuf:"bytes,5,opt,name=create,proto3" json:"create,omitempty"`
	// If true, the resource will not be required to have any attributes associated
	// with resource reconciliation (e.g. status).
	NoReconcile bool `protobuf:"varint,6,opt,name=no_reconcile,json=noReconcile,proto3" json:"no_reconcile,omitempty"`
	// If true, no update method will be generated for the resource. This implies
	// that the resource is immutable.
	NoUpdate bool `protobuf:"varint,7,opt,name=no_update,json=noUpdate,proto3" json:"no_update,omitempty"`
	// Restrictions on the generated delete method.
	Delete *ResourceDescriptor_DeleteRestrictions `protobuf:"bytes,8,opt,name=delete,proto3" json:"delete,omitempty"`
	// if true, the resource is a singleton (only one per scope)
	Singleton bool `protobuf:"varint,9,opt,name=singleton,proto3" json:"singleton,omitempty"`
	// Indicates whether this resource is a pass-through-to-controller resource.
	// If this is true, no_reconcile should also be true.
	PassThrough bool `protobuf:"varint,10,opt,name=pass_through,json=passThrough,proto3" json:"pass_through,omitempty"`
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceDescriptor) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *ResourceDescriptor) GetScope() ResourceDescriptor_Scope {
	if x != nil {
		return x.Scope
	}
	return ResourceDescriptor_SCOPE_UNSPECIFIED
}

func (x *ResourceDescriptor) GetId() *ResourceDescriptor_IdentifierRestrictions {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ResourceDescriptor) GetList() *ResourceDescriptor_ListRestrictions {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ResourceDescriptor) GetCreate() *ResourceDescriptor_CreateRestrictions {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *ResourceDescriptor) GetNoReconcile() bool {
	if x != nil {
		return x.NoReconcile
	}
	return false
}

func (x *ResourceDescriptor) GetNoUpdate() bool {
	if x != nil {
		return x.NoUpdate
	}
	return false
}

func (x *ResourceDescriptor) GetDelete() *ResourceDescriptor_DeleteRestrictions {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *ResourceDescriptor) GetSingleton() bool {
	if x != nil {
		return x.Singleton
	}
	return false
}

func (x *ResourceDescriptor) GetPassThrough() bool {
	if x != nil {
		return x.PassThrough
	}
	return false
}

// FieldBehavior indicates how a given resource field should behave as part of a generated
// service.
type FieldBehavior struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates whether a given field in a resource can participate in sorting
	// in list operations (via order_by).
	Sortable bool `protobuf:"varint,1,opt,name=sortable,proto3" json:"sortable,omitempty"`
	// If set, indicates that this field is to be set by a custom service method.
	MutatedBy *FieldBehavior_MutatedBy `protobuf:"bytes,2,opt,name=mutated_by,json=mutatedBy,proto3" json:"mutated_by,omitempty"`
	// If set, indicates that this field is a system field and cannot be seen or modified by the user.
	Internal bool `protobuf:"varint,3,opt,name=internal,proto3" json:"internal,omitempty"`
	// If set, indicates that this field should be considered unique.
	Unique *FieldBehavior_Unique `protobuf:"bytes,4,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *FieldBehavior) Reset() {
	*x = FieldBehavior{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldBehavior) ProtoMessage() {}

func (x *FieldBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldBehavior.ProtoReflect.Descriptor instead.
func (*FieldBehavior) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *FieldBehavior) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

func (x *FieldBehavior) GetMutatedBy() *FieldBehavior_MutatedBy {
	if x != nil {
		return x.MutatedBy
	}
	return nil
}

func (x *FieldBehavior) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *FieldBehavior) GetUnique() *FieldBehavior_Unique {
	if x != nil {
		return x.Unique
	}
	return nil
}

// Restrictions on IDs for a resource.
type ResourceDescriptor_IdentifierRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The minimum length of IDs.
	MinLen uint32 `protobuf:"varint,1,opt,name=min_len,json=minLen,proto3" json:"min_len,omitempty"`
	// The maximum length if IDs.
	MaxLen uint32 `protobuf:"varint,2,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`
}

func (x *ResourceDescriptor_IdentifierRestrictions) Reset() {
	*x = ResourceDescriptor_IdentifierRestrictions{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_IdentifierRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_IdentifierRestrictions) ProtoMessage() {}

func (x *ResourceDescriptor_IdentifierRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_IdentifierRestrictions.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_IdentifierRestrictions) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceDescriptor_IdentifierRestrictions) GetMinLen() uint32 {
	if x != nil {
		return x.MinLen
	}
	return 0
}

func (x *ResourceDescriptor_IdentifierRestrictions) GetMaxLen() uint32 {
	if x != nil {
		return x.MaxLen
	}
	return 0
}

// Restrictions on listing resources of this type.
type ResourceDescriptor_ListRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum page size for this resource type.
	MaxPageSize int32 `protobuf:"varint,1,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	// Default page size for this resource type, if unspecified.
	DefaultPageSize int32 `protobuf:"varint,2,opt,name=default_page_size,json=defaultPageSize,proto3" json:"default_page_size,omitempty"`
	// Maximum length of the filter field.
	MaxFilterLen int32 `protobuf:"varint,3,opt,name=max_filter_len,json=maxFilterLen,proto3" json:"max_filter_len,omitempty"`
}

func (x *ResourceDescriptor_ListRestrictions) Reset() {
	*x = ResourceDescriptor_ListRestrictions{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_ListRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_ListRestrictions) ProtoMessage() {}

func (x *ResourceDescriptor_ListRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_ListRestrictions.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_ListRestrictions) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceDescriptor_ListRestrictions) GetMaxPageSize() int32 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

func (x *ResourceDescriptor_ListRestrictions) GetDefaultPageSize() int32 {
	if x != nil {
		return x.DefaultPageSize
	}
	return 0
}

func (x *ResourceDescriptor_ListRestrictions) GetMaxFilterLen() int32 {
	if x != nil {
		return x.MaxFilterLen
	}
	return 0
}

// Restrictions on the resource create method.
type ResourceDescriptor_CreateRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of additional fields that will be added to the create
	// request message.
	AdditionalFields []*ResourceDescriptor_CreateRestrictions_Field `protobuf:"bytes,1,rep,name=additional_fields,json=additionalFields,proto3" json:"additional_fields,omitempty"`
}

func (x *ResourceDescriptor_CreateRestrictions) Reset() {
	*x = ResourceDescriptor_CreateRestrictions{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_CreateRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_CreateRestrictions) ProtoMessage() {}

func (x *ResourceDescriptor_CreateRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_CreateRestrictions.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_CreateRestrictions) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ResourceDescriptor_CreateRestrictions) GetAdditionalFields() []*ResourceDescriptor_CreateRestrictions_Field {
	if x != nil {
		return x.AdditionalFields
	}
	return nil
}

// Restrictions on the resource delete method.
type ResourceDescriptor_DeleteRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of additional fields that will be added to the delete
	// request message.
	AdditionalFields []*ResourceDescriptor_DeleteRestrictions_Field `protobuf:"bytes,1,rep,name=additional_fields,json=additionalFields,proto3" json:"additional_fields,omitempty"`
}

func (x *ResourceDescriptor_DeleteRestrictions) Reset() {
	*x = ResourceDescriptor_DeleteRestrictions{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_DeleteRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_DeleteRestrictions) ProtoMessage() {}

func (x *ResourceDescriptor_DeleteRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_DeleteRestrictions.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_DeleteRestrictions) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ResourceDescriptor_DeleteRestrictions) GetAdditionalFields() []*ResourceDescriptor_DeleteRestrictions_Field {
	if x != nil {
		return x.AdditionalFields
	}
	return nil
}

// Field defines a field that should be included in a create request.
// Currently only native protobuf types are supported (e.g. primitives,
// maps of primitives, etc.).
type ResourceDescriptor_CreateRestrictions_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of the field. This will appear as the comment above the
	// field in the generated proto. If it contains carriage returns (`\n`),
	// The comment will be split over multiple lines.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Specifies the exact text for the field type. For use with native
	// protobuf types only.
	NativeType string `protobuf:"bytes,3,opt,name=native_type,json=nativeType,proto3" json:"native_type,omitempty"`
}

func (x *ResourceDescriptor_CreateRestrictions_Field) Reset() {
	*x = ResourceDescriptor_CreateRestrictions_Field{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_CreateRestrictions_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_CreateRestrictions_Field) ProtoMessage() {}

func (x *ResourceDescriptor_CreateRestrictions_Field) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_CreateRestrictions_Field.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_CreateRestrictions_Field) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *ResourceDescriptor_CreateRestrictions_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor_CreateRestrictions_Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceDescriptor_CreateRestrictions_Field) GetNativeType() string {
	if x != nil {
		return x.NativeType
	}
	return ""
}

// Field defines a field that should be included in a delete request.
// Currently only native protobuf types are supported (e.g. primitives,
// maps of primitives, etc.).
type ResourceDescriptor_DeleteRestrictions_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of the field. This will appear as the comment above the
	// field in the generated proto. If it contains carriage returns (`\n`),
	// The comment will be split over multiple lines.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Specifies the exact text for the field type. For use with native
	// protobuf types only.
	NativeType string `protobuf:"bytes,3,opt,name=native_type,json=nativeType,proto3" json:"native_type,omitempty"`
}

func (x *ResourceDescriptor_DeleteRestrictions_Field) Reset() {
	*x = ResourceDescriptor_DeleteRestrictions_Field{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor_DeleteRestrictions_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor_DeleteRestrictions_Field) ProtoMessage() {}

func (x *ResourceDescriptor_DeleteRestrictions_Field) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor_DeleteRestrictions_Field.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor_DeleteRestrictions_Field) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *ResourceDescriptor_DeleteRestrictions_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor_DeleteRestrictions_Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceDescriptor_DeleteRestrictions_Field) GetNativeType() string {
	if x != nil {
		return x.NativeType
	}
	return ""
}

// MutatedBy specifies a custom gRPC service and method that should be generated
// for setting the field. The request for the generated method will contain all fields
// that reference the method in their annotation.
type FieldBehavior_MutatedBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the custom service to be generated for setting the field.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// The method in the custom service for setting the field.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *FieldBehavior_MutatedBy) Reset() {
	*x = FieldBehavior_MutatedBy{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldBehavior_MutatedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldBehavior_MutatedBy) ProtoMessage() {}

func (x *FieldBehavior_MutatedBy) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldBehavior_MutatedBy.ProtoReflect.Descriptor instead.
func (*FieldBehavior_MutatedBy) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FieldBehavior_MutatedBy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *FieldBehavior_MutatedBy) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// Unique specifies uniqueness constraints for a field. If set, the field will be considered
// unique within its collection. An attempt to create/update a resource containing a
// value that already exists in the collection will be rejected with INVALID_ARGUMENT.
type FieldBehavior_Unique struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FieldBehavior_Unique) Reset() {
	*x = FieldBehavior_Unique{}
	mi := &file_aviatrix_api_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldBehavior_Unique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldBehavior_Unique) ProtoMessage() {}

func (x *FieldBehavior_Unique) ProtoReflect() protoreflect.Message {
	mi := &file_aviatrix_api_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldBehavior_Unique.ProtoReflect.Descriptor instead.
func (*FieldBehavior_Unique) Descriptor() ([]byte, []int) {
	return file_aviatrix_api_annotations_proto_rawDescGZIP(), []int{1, 1}
}

var file_aviatrix_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ResourceDescriptor)(nil),
		Field:         2901212,
		Name:          "aviatrix.api.resource",
		Tag:           "bytes,2901212,opt,name=resource",
		Filename:      "aviatrix/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldBehavior)(nil),
		Field:         2901213,
		Name:          "aviatrix.api.field_behavior",
		Tag:           "bytes,2901213,opt,name=field_behavior",
		Filename:      "aviatrix/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional aviatrix.api.ResourceDescriptor resource = 2901212;
	E_Resource = &file_aviatrix_api_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional aviatrix.api.FieldBehavior field_behavior = 2901213;
	E_FieldBehavior = &file_aviatrix_api_annotations_proto_extTypes[1]
)

var File_aviatrix_api_annotations_proto protoreflect.FileDescriptor

var file_aviatrix_api_annotations_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8d, 0x0a, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x26, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x12, 0x47, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x02, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x4b, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x33, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6e, 0x6f, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x6f, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6e, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4b,
	0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x73,
	0x73, 0x5f, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x70, 0x61, 0x73, 0x73, 0x54, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x1a, 0x4a, 0x0a, 0x16,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x1a, 0x88, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x0a,
	0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x4c, 0x65, 0x6e, 0x1a, 0xdc, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x66, 0x0a, 0x11, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x10, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x1a, 0x5e, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x1a, 0xdc, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x66, 0x0a, 0x11, 0x61, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x10, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x1a, 0x5e, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x5d, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x43,
	0x4f, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x47, 0x4c, 0x4f, 0x42, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x46, 0x41, 0x42,
	0x52, 0x49, 0x43, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x03,
	0x22, 0x92, 0x02, 0x0a, 0x0d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x44,
	0x0a, 0x0a, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x4d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x52, 0x09, 0x6d, 0x75, 0x74, 0x61, 0x74,
	0x65, 0x64, 0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x12, 0x3a, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x1a, 0x3d, 0x0a, 0x09,
	0x4d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x1a, 0x08, 0x0a, 0x06, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x3a, 0x60, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xdc, 0x89, 0xb1, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x76,
	0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x3a, 0x64, 0x0a, 0x0e, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdd, 0x89, 0xb1, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x0d,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x42, 0xb5, 0x01,
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x61,
	0x70, 0x69, 0x42, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x41, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x6f, 0x2f, 0x61, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69,
	0x3b, 0x61, 0x70, 0x69, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x41, 0x41, 0x58, 0xaa, 0x02, 0x0c, 0x41,
	0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x41, 0x70, 0x69, 0xca, 0x02, 0x0c, 0x41, 0x76,
	0x69, 0x61, 0x74, 0x72, 0x69, 0x78, 0x5c, 0x41, 0x70, 0x69, 0xe2, 0x02, 0x18, 0x41, 0x76, 0x69,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x5c, 0x41, 0x70, 0x69, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x41, 0x76, 0x69, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x3a, 0x3a, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aviatrix_api_annotations_proto_rawDescOnce sync.Once
	file_aviatrix_api_annotations_proto_rawDescData = file_aviatrix_api_annotations_proto_rawDesc
)

func file_aviatrix_api_annotations_proto_rawDescGZIP() []byte {
	file_aviatrix_api_annotations_proto_rawDescOnce.Do(func() {
		file_aviatrix_api_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_aviatrix_api_annotations_proto_rawDescData)
	})
	return file_aviatrix_api_annotations_proto_rawDescData
}

var file_aviatrix_api_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aviatrix_api_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aviatrix_api_annotations_proto_goTypes = []any{
	(ResourceDescriptor_Scope)(0),                       // 0: aviatrix.api.ResourceDescriptor.Scope
	(*ResourceDescriptor)(nil),                          // 1: aviatrix.api.ResourceDescriptor
	(*FieldBehavior)(nil),                               // 2: aviatrix.api.FieldBehavior
	(*ResourceDescriptor_IdentifierRestrictions)(nil),   // 3: aviatrix.api.ResourceDescriptor.IdentifierRestrictions
	(*ResourceDescriptor_ListRestrictions)(nil),         // 4: aviatrix.api.ResourceDescriptor.ListRestrictions
	(*ResourceDescriptor_CreateRestrictions)(nil),       // 5: aviatrix.api.ResourceDescriptor.CreateRestrictions
	(*ResourceDescriptor_DeleteRestrictions)(nil),       // 6: aviatrix.api.ResourceDescriptor.DeleteRestrictions
	(*ResourceDescriptor_CreateRestrictions_Field)(nil), // 7: aviatrix.api.ResourceDescriptor.CreateRestrictions.Field
	(*ResourceDescriptor_DeleteRestrictions_Field)(nil), // 8: aviatrix.api.ResourceDescriptor.DeleteRestrictions.Field
	(*FieldBehavior_MutatedBy)(nil),                     // 9: aviatrix.api.FieldBehavior.MutatedBy
	(*FieldBehavior_Unique)(nil),                        // 10: aviatrix.api.FieldBehavior.Unique
	(*descriptorpb.MessageOptions)(nil),                 // 11: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),                   // 12: google.protobuf.FieldOptions
}
var file_aviatrix_api_annotations_proto_depIdxs = []int32{
	0,  // 0: aviatrix.api.ResourceDescriptor.scope:type_name -> aviatrix.api.ResourceDescriptor.Scope
	3,  // 1: aviatrix.api.ResourceDescriptor.id:type_name -> aviatrix.api.ResourceDescriptor.IdentifierRestrictions
	4,  // 2: aviatrix.api.ResourceDescriptor.list:type_name -> aviatrix.api.ResourceDescriptor.ListRestrictions
	5,  // 3: aviatrix.api.ResourceDescriptor.create:type_name -> aviatrix.api.ResourceDescriptor.CreateRestrictions
	6,  // 4: aviatrix.api.ResourceDescriptor.delete:type_name -> aviatrix.api.ResourceDescriptor.DeleteRestrictions
	9,  // 5: aviatrix.api.FieldBehavior.mutated_by:type_name -> aviatrix.api.FieldBehavior.MutatedBy
	10, // 6: aviatrix.api.FieldBehavior.unique:type_name -> aviatrix.api.FieldBehavior.Unique
	7,  // 7: aviatrix.api.ResourceDescriptor.CreateRestrictions.additional_fields:type_name -> aviatrix.api.ResourceDescriptor.CreateRestrictions.Field
	8,  // 8: aviatrix.api.ResourceDescriptor.DeleteRestrictions.additional_fields:type_name -> aviatrix.api.ResourceDescriptor.DeleteRestrictions.Field
	11, // 9: aviatrix.api.resource:extendee -> google.protobuf.MessageOptions
	12, // 10: aviatrix.api.field_behavior:extendee -> google.protobuf.FieldOptions
	1,  // 11: aviatrix.api.resource:type_name -> aviatrix.api.ResourceDescriptor
	2,  // 12: aviatrix.api.field_behavior:type_name -> aviatrix.api.FieldBehavior
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	11, // [11:13] is the sub-list for extension type_name
	9,  // [9:11] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_aviatrix_api_annotations_proto_init() }
func file_aviatrix_api_annotations_proto_init() {
	if File_aviatrix_api_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aviatrix_api_annotations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_aviatrix_api_annotations_proto_goTypes,
		DependencyIndexes: file_aviatrix_api_annotations_proto_depIdxs,
		EnumInfos:         file_aviatrix_api_annotations_proto_enumTypes,
		MessageInfos:      file_aviatrix_api_annotations_proto_msgTypes,
		ExtensionInfos:    file_aviatrix_api_annotations_proto_extTypes,
	}.Build()
	File_aviatrix_api_annotations_proto = out.File
	file_aviatrix_api_annotations_proto_rawDesc = nil
	file_aviatrix_api_annotations_proto_goTypes = nil
	file_aviatrix_api_annotations_proto_depIdxs = nil
}
